import MarkWirf from '../blogassets/MarkWirfs.jpg'
import Covid19 from '../blogassets/covid19difficulty.jpg'
import tools from '../blogassets/tools.jpg'
import RNW from '../blogassets/laptop.jpg'
import gregRobertson  from '../blogassets/gregrobertson.png'
import harryreeder from '../blogassets/HarryReeder.jpg'
import CIDA100 from '../blogassets/CIDA100.png'
import balancingworkandfamily from '../blogassets/canstockphoto.jpg'
import orcascropped from '../blogassets/orcascropped.jpg'
import fireflowtests from '../blogassets/fireflow.jpg'
import automation from '../blogassets/automation.jpg'
import cealingSquares from '../blogassets/cealingSquares.jpg'
import VRF from '../blogassets/VRFTechnology.jpg'
import intern from '../blogassets/Jenna.jpg'
import troubleshooting from '../blogassets/troubleshooting.jpg'
import utilityCoordination from '../blogassets/utilityCoord.jpg'
import sistersmaintance from '../blogassets/sistersmaintenance.jpg'
import lessonCFD from '../blogassets/CFDLessonimage.jpg'
import LowHanging from '../blogassets/energyUpgrades.jpg'

import enginerd from '../blogassets/theenginerd.jpg'
import humansnotnumbers from '../blogassets/HumanNotNumbers.jpg'
import GreenEnergy from '../blogassets/GreenEnergy.jpg'


export {MarkWirf, Covid19, tools, RNW, gregRobertson, harryreeder, CIDA100, balancingworkandfamily, orcascropped, fireflowtests, automation, cealingSquares, VRF, intern, troubleshooting, utilityCoordination, sistersmaintance, lessonCFD, LowHanging,  enginerd, humansnotnumbers, GreenEnergy }