// constants/projectsData.ts
import { StaticImageData } from 'next/image';
import {
  commercial,
  lesSchawb,
  maxim,
  comcast,
  visionplaza,
  walnutplanet,
  communications,
  att,
  comcast2,
  miscWireless,
  sprintNextel,
  verizon,
  community,
  CEC3,
  cheCultureCenterLEED,
  noviceSkatePark,
  TualatinHillsPark,
  education,
  Alberta,
  resersFineFoods,
  donPacho,
  oregonLottery,
  riverParkway,
  energy,
  schools,
  hillsboroHigh,
  millerEducation,
  threeRiversSchool,
  TualatinElementary,
  government,
  bonnevillePowerUpgrade,
  bonnevilleCoolingAssessment,
  fallCreekHatchery,
  USPS,
  health,
  bendUrology,
  CorvallisClinic,
  westHillsGastro,
  willametteFallsCommons,
  industrial,
  columbiaSteel,
  kochCarbonSulfur,
  lehighCement,
  malhuerLumber,
  tokaiCarbonFurnance,
  LEED,
  kcoffeeBeanInter,
  PWBMeterShop,
  wuanaCredit,
  youthFam,
  municipal,
  bendWell,
  jointWaterCommision,
  municipalReclamation,
  seasidePetersonPointReservoir,
  redmonReservoir,
} from '../ProjectsAssets/ProjectAssetsImports';

export type SubCategory = {
  image: StaticImageData;
  subtitle: string;
  SEOTitle: string;
  location: string;
  service1?: string;
  service2?: string;
  service3?: string;
  service4?: string;
  service5?: string;
  descriptionsummary: string;
  description1: string;
  description2?: string;
  description3?: string;
  description4?: string;
};

export type Project = {
  id: string;
  img: StaticImageData;
  title: string;
  subCategories: SubCategory[];
};

export const projects: Project[] = [
  {
    id: 'commercial',
    img: commercial,
    title: "Commercial",
    subCategories: [
      {
        image: walnutplanet,
        subtitle: "Walnut-Village-Retirement-Center",
        SEOTitle: "Walnut Village Retirement center",
        location: "Anaheim, california",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "R&W Engineering provided engineering design services for a 7.7 acre returement community.",
        description1: "The facility includes the 375,000 square feet main housing building, with 147 independent living units and a 14 unit dementia wing. There are 9 independent living cottages, a commerical kitchen, indoor swimming pool and jacuzzi, exercise area, speciality eateries, lounges, craft areas, underground parking area, offices, recreational areas and ancillary spaces. This design incorporates a large 9000 square foot commercial kitchen and dining area serving approximately 250 Reutrement Center residents. R&W's design included HVAC, plumbing, power, emergency power, security, nurse call, interior and site lighting, fire proetction, fire alarm and pateint alert/detection systems and low-volatage design.",
      },
      {
        image: visionplaza,
        subtitle: "Vision-Plaza",
        SEOTitle: "Vision Plaza",
        location: "Bend, Oregon",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "R&W provided mechanical, electrical and fire sprinkler design services for this 38,000 square foot three story building with an underground parking garage in the basement level.",
        description1: "This project was completed in a Core and Shell followed by Tenant Improvement design structure. R&W completed the Core and Shell design which included a variable air volume system with zone control VAV boxes for future tenants. The electrical system included a Square D Power Logic sub-metering system to allow individual tracking and billing of tenant electrical use. HVAC systems are controlled by a DDC system that allows tracking of afterhours override for tracking and billing for additional HVAC system use. In addition to the Core and Shell design R&W has completed 12 tenant improvement designs in the building.",
      },
      {
        image: maxim,
        subtitle: "Maxim-Integrated",
        SEOTitle: "Maxim Integrated",
        location: "Beaverton, Oregon",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "",
        description1: "R&W Engineering completed this project for Maxim. It was a two-part project that included both a new office building and a major remodel of the existing computer labs, clean room, and support areas. R&W provided mechanical, electrical, and data/fire alarm design. In Phase I, R&W designed HVAC, plumbing, power, lighting, data, and fire alarm systems for the 93,000 square foot, 3-story office building. The building was designed with an open floor plan that included multiple conference rooms, a 3-story lobby, and a cafeteria with a full kitchen. The HVAC system used large VAV rooftop units serving fan powered VAV boxes for individual zone controls. For the lighting, energy efficient suspended direct-indirect fixtures were chosen and implemented.",
        description2: "Once completed, the building received a LEED Silver rating. In support of the LEED effort, R&W designed eight electric vehicle charging stations, low flow plumbing fixtures, efficient site lighting that did not trespass to adjacent properties, and efficient HVAC systems.",
        description3: "Phase 2 was an approximately 20,000 square foot major remodel of the existing computer labs, clean room, and support areas. This phase was a conversion of existing office spaces into test and design lab spaces, including a 5,000 square foot clean room test lab. R&W provided HVAC, plumbing, power, data, and fire alarm design for all computer labs, electronic workshops, and supporting office areas.",
        description4: "The design also included extensive process piping systems for compressed air, nitrogen, RO/DI water, and other services. The lighting was replaced to match the lighting of the new office building.",
      },
      {
        image: lesSchawb,
        subtitle: "Les-Schwab-Tire-Center",
        SEOTitle: "Les Schawb Tire Center",
        location: "WA, OR, ID, CA, UT, CO, NV",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "Les Schwab Tire Centers are a popular West Coast retail tire chain with a strong reputation for customer care.",
        description1: "They specialize in tires, alignment, shock absorbers, batteries and brakes. R&W has provided design services for over 50 Les Schwab Tire Center stores throughout the western United States. Each store includes showroom and retail space, warehouse space and up to ten complete service bays including an alignment pit. R&W designs independent HVAC systems for each area, plumbing for public and service areas, compressed air distribution in the service bays, lighting and power systems for all areas, schematic fire sprinkler systems, fire alarm systems and security systems for design/build contractor's use, and telephone/data system interconnections. Design services also include full utility company coordination for gas, power, telephone and cable television building services, building envelope energy calculations, lighting analysis and calculations and energy code forms as required by each jurisdiction.",
      },
      {
        image: comcast,
        subtitle: "Comcast-Corvallis-New-Headend-Building",
        SEOTitle: "Comcast Corvallis New Headend Building ",
        location: "Troutdale, Oregon",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "R&W Engineering, Inc. provided mechanical and electrical engineering services for this new 9,500 square foot Comcast Building.",
        description1: "This project was a 9,500 square foot addition to an existing Comcast facility. The addition included a 7,000 square foot Headend (data center) and a 2,500 square foot power room for both AC and DC power systems serving the Headend. R&W's design included N+1 redundant HVAC systems, humidity control, and redundant 1 megawatt generators with redundant cross over fuel systems.",
        description2: "R&W designed a unique redundant HVAC system using relatively common rooftop HVAC units mounted on the ground and ducted in parallel to achieve N+1 redundancy. For humidity control, some units operated in cooling while one cycled heating to provide reheat. This unique solution was a cost-effective solution to a complex problem within the project budget.",
        description3: "The electrical systems, both AC and DC, were fully redundant, including two 1 megawatt generators. R&W provided full design for all systems. To allow for additional generator fuel capacity, R&W designed a method from pumping fuel from one skid tank to the other.",
        description4: "R&W also participated in the design of a three-level auxiliary framing system to support AC power, DC power, and HVAC ductwork with lighting above and below the framing. This was achieved using Revit building information modeling.",
      },
    ],
  },
  {
    id: "communications",
    img: communications,
    title: "Communications",
    subCategories: [
      {
        image: att,
        subtitle: "AT&TCingular",
        SEOTitle: "AT&T Cingular",
        location: "Multiple location's throughout Oregon and Washington",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "Provided M/E/P engineering for over 600 sites in Oregon and Washington.",
        description1: "Services included power and telco utility coordination, soil resistivity testing, lighting and power design, ground system design, HVAC, DC exhaust system design, hydrogen sensing for battery alarm and piping design for generator fuel supply.",
      },
      {
        image: comcast2,
        subtitle: "Comcast-Communications",
        SEOTitle: "Comcast Communications",
        location: "Multiple location's throughout Oregon and Washington",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "R&W works directly with Comcast to provide M/E/P design and construction administration services for a broad range of projects.",
        description1: "Project size varies from HVAC studies for equipment additions to the design of completely new head-end switching facilities. The newest facilities include separate A&B 10,000 amp, 48 VDC power plants.",
      },
      {
        image: verizon,
        subtitle: "Verizon-Wireless",
        SEOTitle: "Verizon Wireless",
        location: "Multiple location's throughout Oregon and Washington",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "Provided M/E/P engineering for over 850 sites in Oregon and Washington.",
        description1: "Services included power and telco utility coordination, soil resistivity testing, lighting and power design, ground system design, HVAC, DC exhaust system design, hydrogen sensing for battery, alarm and piping design for generator fuel supply.",
      },
      {
        image: sprintNextel,
        subtitle: "Sprint/Nextel",
        SEOTitle: "Sprint Nextel",
        location: "Multiple location's throughout Oregon and Washington",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "Provided M/E/P engineering for over 400 sites in Oregon and Washington.",
        description1: "Services included power and telco utility coordination, soil resistivity testing, lighting and power design, ground system design, HVAC, DC exhaust system design, hydrogen sensing for battery, alarm and piping design for generator fuel supply.",
      },
      {
        image: miscWireless,
        subtitle: "Miscellaneous",
        SEOTitle: "Miscellaneous",
        location: "Multiple location's throughout Oregon and Washington",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "Provided M/E/P engineering for 385+ sites in Oregon and Washington for a variety of carriers such as Voicestream, Clearwire, US West, Qwest, Western PCS, WOW, and Cricket.",
        description1: "Services included power and telco utility coordination, soil resistivity testing, lighting and power design, ground system design, HVAC, DC exhaust system design, hydrogen sensing for battery, alarm and piping design for generator fuel supply.",
      },
    ],
  },
  {
    id: "community",
    img: community,
    title: "Community",
    subCategories: [
      {
        image: TualatinHillsPark,
        subtitle: "Tualatin-Hills-Parks-and-Recreation-District:-Rock-Creek-Recreation-Facility",
        SEOTitle: "Tualatin Hills Parks and Recreation District: Rock Creek Recreation Facility",
        location: "Beaverton, Oregon",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        descriptionsummary: "The project is a new major sports complex situated on a 32 acre site adjacent to the Portland Community College Rock Creek campus and adjoining residential developments.",
        description1: "The project consists of four 300-foot radius Softball Fields with three practice Football Fields overlaid in the outfield area, two regulation Soccer fields with two overlaid Football Fields, scoreboards, six outdoor tennis courts, pedestrian pathways, restrooms, concessions, picnic pavilion, playground area, parking and a maintenance yard. All sports venues are illuminated for night play with Musco Lighting sports field lighting systems in strict compliance with Washington County light trespass ordinances. An electrical distribution and control system is designed to support and control all sports field lighting, parking lot lighting, pedestrian pathway lighting, and feeders to concessions, restrooms and maintenance yard.",
      },
      {
        image: cheCultureCenterLEED,
        subtitle: "Chehalem-Cultural-Center-LEED®-Silver",
        SEOTitle: "Chehalem Cultural Center LEED® Silver",
        location: "Newberg, Oregon",
        service1: "Mechanical Engineering",
        service2: "Electrical Engineering",
        service3: "Energy Services",
        service4: "Commissioning",
        descriptionsummary: "Chehalem Park and Recreation District hired R&W Engineering to provide electrical and mechanical design services, LEED energy analysis, LEED services, and commissioning services for this community/cultural center pursuing LEED Silver certification.",
        description1: "This 2-story building originally served as an elementary school and this project involved converting it into a cultural center. R&W hired and worked closely with the commissioning agent to provide fundamental and enhanced commissioning to meet LEED's requirements.",
        description2: "R&W has been providing mechanical and electrical engineering services for this project since it began in 2004. The project included the seismic upgrade, demolition of existing HVAC, plumbing and electrical systems and design for new HVAC, plumbing and electrical systems in a phased construction. Work has included public meetings with the park and recreation department to explain quality of existing systems and options for upgrade. This project uses a water source heat pump system, a high efficiency boiler and cooling tower, daylight lighting controls, occupancy sensors for lighting control, demand control ventilation, solar water heating, high efficiency condensing water heater and indirect lighting.",
      },
      {
        image: noviceSkatePark,
        subtitle: "Tualatin-Hills-Parks-and-Recreation-Distrct-Novice-Skate-Park",
        SEOTitle: "Tualatin Hills Parks and Recreation Distrct: Novice-Skate Park",
        location: "Beaverton, Oregon",
        service1: "Mechanical Engineering",
        descriptionsummary: "R&W provided electrical design services extending the existing electrical distribution and lighting control to energize a lighting system at this new Novice Skate Park.",
        description1: "Illuminating the Novice Skate Park is intended to provide a safe,well lighted, environment for use after dusk. Placement and aiming of luminaires is intended to minimize creation of shadows at the skate park features.",
        },

        {
            image: CEC3,
            subtitle: "Chehalem-Cultural-Center-Culinary-Education-Center",
            SEOTitle: "Chehalem Cultural Center: Culinary Education Center",
            location: "Newburg, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "This is the third project R&W has completed for this client.",
            description1: "R&W provided plumbing, HVAC, lighting, and power design for a new Culinary Education Center and new public restrooms for a courtyard in the existing Chehalem Cultural Center.",
            description2: "This project included extending existing building plumbing and HVAC piping systems to serve new plumbing fixtures and HVAC water source heat pumps in the new culinary center. As this was one of several build-out projects, R&W included water flow measurements to determine if the HVAC condenser water system had the expected capacity to suit the needs of the building.",
            description3: "The electrical design included ceiling drops to allow for multiple table arrangements that might be required for different teaching and learning needs.",
            description4: "This was the third project R&W worked on in a continuing build on the Chehalem Cultural Center. R&W also worked on the first big remodel and the remodel of the ballroom.",
          },
        ],
      },
      {
        id: "education",
        img: education,
        title: "Education",
        subCategories: [
          {
            image: TualatinElementary,
            subtitle: "Tigard-Tualatin-School-Distrct-Tualatin Elementary",
            SEOTitle: "Tigard: Tualatin School Distrct: Tualatin Elementary",
            location: "Tualatin, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "Due to changing demographics and population growth in the city of Tigard, the Tigard-Tualatin School District decided that a new elementary school was needed.",
            description1: "R&W Engineering worked closely with the school district and the rest of the design team to provide HVAC, plumbing, and electrical consulting services for the new school. This involved close communication with the school district to make sure that all of their requirements were met. The final result was a new, modern school with the latest building technology.",
          },
          {
            image: threeRiversSchool,
            subtitle: "Bend-La-Pine-School-District-Three-Rivers-Elementary",
            SEOTitle: "Bend La Pine School District, Three Rivers Elementary",
            location: "Tualatin, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W provided Mechanical, Electrical, Plumbing and Low Voltage design services for 2 new buildings that include a gymnasium and classrooms building, as well as a remodel in the administration offices.",
            description1: "The project also includes the replacement of the boilers in the individual buildings on the campus with a campus wide single central plant and snow melt for exterior walkways. Low voltage design included program clock, page, fire alarm, security, and video and telecommunications (voice and data) systems design.",
          },
          {
            image: millerEducation,
            subtitle: "Miller-Education-Center",
            SEOTitle: "Miller Education Center",
            location: "Hillsboro, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "When the Hillsboro School District wanted to convert an existing elementary school, David Hill Elementary, into an alternative learning center, they hired R&W for a remodel and upgrade to provide Mechanical, Electrical, plumbing design and retro-commissioning.",
            description1: "Retro-commissioning work included thorough analysis of their existing boiler, ventilation and control systems. R&W was able to provide a detailed analysis of these existing systems and was able to outline which items were immediate priorities to be fixed or replaced and which items could be worked on at a later date.",
          },
          {
            image: hillsboroHigh,
            subtitle: "HillsBoro-School-District,-Hillsboro-High-School-Remodel",
            SEOTitle: "Hillsboro school district, HIllsboro High School Remodel",
            location: "Hillsboro, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W provided mechanical, electrical and plumbing design for the remodel of the locker rooms, team rooms, restrooms, office, storage, and laundry rooms.",
            description1: "Lighting design included emergency lighting and egress lighting at exterior doors. Lighting controls were added to meet the Oregon Lighting Compliance codes.",
          },
          {
            image: Alberta,
            subtitle: "Alberta-Rider-Elementary-School",
            SEOTitle: "Alberta-Rider-Elementary-School",
            location: "Tigard, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "Alberta Rider Elementary is a new K-5 school serving the needs of the community in the Bull Mountain area of the Tigard Tualatin School District.",
            description1: "This 70,000 square foot school includes full gymnasium, cafeteria, kitchen, library, administrative offices in addition to classrooms. R&W designed an HVAC system consisting of rooftop variable air handlers serving individual terminal units with reheat in each zone or classroom to provide excellent zoned comfort conditioning. The lighting for the building is primarily energy efficient indirect lighting providing glare free lighting and cost savings to the owner. This design incorporates many components to provide a comfortable and efficient environment for the staff, teacher and students of Tigard Tualatin School District.",
          },
        ],
      },
      {
        id: "energy",
        img: energy,
        title: "Energy",
        subCategories: [
          {
            image: resersFineFoods,
            subtitle: "Reser's-Fine-Foods",
            SEOTitle: "Reser's Fine Foods",
            location: "Beaverton, Oregon",
            service1: "Energy",
            descriptionsummary: "Reser's Fine Foods is a major food production and distribution facility. R&W was contracted by Energy Trust of Oregon's Existing Building Program, and worked closely with Key Mechanical, to provide a full energy and cost analysis of various energy upgrades.",
            description1: "These upgrades were proposed by Key Mechanical and aimed at improving the energy efficiency of multiple low temperature and medium temperature food storage rooms. Some of the measures analyzed included intelligent defrost, variable speed drives on compressors, condenser and evaporator fan motors and heat recovery from the cold storage to preheat domestic hot water. Reser's implemented many of the upgrades identified and R&W used the energy analysis to secure Energy Trust of Oregon incentive money and State of Oregon tax credits for Reser's.",
          },
          {
            image: donPacho,
            subtitle: "Don-Pancho",
            SEOTitle: "Don Pancho",
            location: "Salem, Oregon",
            service1: "Energy",
            descriptionsummary: "R&W Engineering was contracted by Reser's Fine Foods to provide an energy analysis and savings calculations associated with a new tortilla line at Don Pancho.",
            description1: "This report was used by BPA's Energy Smart Industrial Program, Salem Electric, Energy Trust of Oregon and Oregon Department of Energy to award incentives for the higher efficiency line. One year of production data and utility data from the facility manager and two weeks of electrical data logging on the existing lines coupled with input from plant personnel on typical operations was utilized as part of this analysis. Over 319,000 kWh of annual electrical savings and 200,000 therms of annual gas savings were identified saving the owner $115,000 annually. In addition, this project was eligible to receive $680,000 in incentive money from the above utility providers and agencies.",
          },
          {
            image: oregonLottery,
            subtitle: "Oregon-State-Lottery",
            SEOTitle: "Oregon State Lottery",
            location: "Salem, Oregon",
            service1: "Energy",
            descriptionsummary: "R&W provided energy services for Oregon State Lottery.",
            description1: "R&W provided energy services through the Energy Trust of Oregon and mechanical engineering services directly to the Oregon State Lottery for several recent upgrades to their central office in Salem, Oregon.  Energy services were paid for by Energy Trust of Oregon and included a Technical Analysis Study that quantified electric and gas costs and savings for several building improvements, including: A modern, building wide HVAC digital control system and a high-efficiency server room HVAC system. The server room HVAC upgrade used a state-of-the-art refrigerant economizer system to take advantage of Oregon's mild climate. This system provides free cooling  for much of the year without compromising the server room air quality by using outside air. The Lottery has implemented the HVAC controls and server room HVAC upgrades recently and has plans to make the remaining upgrades, all with incentive assistance from Energy Trust of Oregon. R&W was able to use the information gained from the energy studies and move right into assistance with design and construction. R&W prepared performance build specifications for these upgrades, assisted in the bid opening and award, and verified that the final installation met specifications."
          },
          {
            image: riverParkway,
            subtitle: "River-Parkway-Building",
            SEOTitle: "River Parkway Building",
            location: "Portland, Oregon",
            service1: "Energy",
            descriptionsummary: "River Parkway is an 89,000 square foot, eight-story commercial office building located in Portland's South Waterfront district.",
            description1: "It consists of commercial office space, three floors of parking and a restaurant on the first floor. R&W Engineering was contracted by Energy Trust of Oregon's Existing Building Program to identify potential energy upgrades and provide a full energy and cost analysis. The 10 upgrades identified included high-efficiency boilers, premium-efficiency fan motors and variable speed drives, demand control ventilation and premium-efficiency lighting and controls. Besides the incentives available from ETO and the State of Oregon, if implemented, the measures identified had an annual savings of 82,104 kWh and 6,283 therms. R&W was later hired by the building's Owner, Urban Renaissance Group, and assisted their team in securing a LEED for Existing Buildings: Operation and Maintenance Gold rating. The report and analysis prepared for ETO assisted in this work.",
          },
          {
            image: schools,
            subtitle: "Oregon-Department-of-Energy-School-Energy-Audits-49-Schools",
            SEOTitle: "Oregon Department of Energy: School Energy Audits, 49 Schools",
            location: "Throughout Oregon",
            service1: "Energy",
            descriptionsummary: "R&W was hired by the Oregon Department of Energy to provide 49 Oregon Schools with an energy audit to determine weatherization, lighting and mechanical systems upgrades that can lower energy costs and create construction jobs..",
            description1: "R&W completed all audits ahead of ODOE's schedule by 2 months. Recommended upgrades included new windows and doors, weather sealing, adding insulation, interior and exterior lighting upgrades, HVAC upgrades, domestic hot water upgrades, building control system upgrades and operational procedures. This included high schools, middle schools, elementary schools, administrative offices, education centers, maintenance facilities and bus barns. There were 15 school districts involved that included Bend-LaPine, Black Butte, Crook County, Hood River, Mitchell, Morrow, Sisters, Spray, Dayville, John Day, Long Creek, Monument, Prairie City, Canby and Ione School Districts.",
          },
        ],
      },
      {
        id: "government",
        img: government,
        title: "Government",
        subCategories: [
          {
            image: bonnevillePowerUpgrade,
            subtitle: "Bonneville-Power-Administration-Business-Critical-Power-Upgrade",
            SEOTitle: "Bonneville Power Administration: Business Critical Power Upgrade",
            location: "Portland, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W Engineering, Inc. completed a project working with BPA to design, document, test and commission the new Business Critical Power Upgrade for Portland Headquarters.",
            description1: "Electrical Engineering was provided for new A and B 2500A normal and emergency services. Two existing 500kW generators were removed and replaced with 750k generators. Mechanical Engineering services include fuel supply, exhaust, and ventilation for two new 750 kW generators and one existing 750kW generator located in the penthouse. The three 750kW generators were paralleled to provide a 2500A, 480volt source.",
          },
          {
            image: bonnevilleCoolingAssessment,
            subtitle: "Bonneville-Power-Administration,-Critical-Cooling-Assessment",
            SEOTitle: "Boneville Power Administration, Critical Cooling Assessment",
            location: "Spokane, Washington",
            service1: "Mechanical Engineering",
            descriptionsummary: "R&W provided a complete assessment report to document existing conditions and make suggestions for possible changes for the cooling system in the existing Data Center and the Munro Control Center Facility.",
            description1: "Report included analysis of the age and general condition of the equipment providing air conditioning to both the Data Center and the entire facility, and how they affected one another. The assessment included estimated costs to implement suggested changes. R&W also provided complete computational fluid dynamics (CFD) analysis of the air flows within the Data Center, for existing conditions as well as several alternate arrangements for upgrade.",
          },
          {
            image: fallCreekHatchery,
            subtitle: "Fall-Creek-Hatchery-Research-Center",
            SEOTitle: "Fall Creek Hatchery Research Center",
            location: "Alsea, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering Automation",
            descriptionsummary: "The Hatchery Research Center at Fall Creek included additions to and modifications of the existing Fall Creek Hatchery facility to support hatchery, harvest, habitat management and other related research.",
            description1: "Project components include a learning research building, approximately 12,000 SF, a new dormitory, approximately 4,000 SF, maintenance shop, restrooms, storage and residences. The project also includes design of hatchery related structures, including simulated streams and research rearing ponds, site infrastructure improvements, including hatchery water supply and distribution piping, settling pond for hatchery water supply, disinfection of hatchery water supply or portion thereof, domestic water supply, treatment, storage, and distribution, fire protection system, hatchery wastewater collection, treatment and disposal, domestic wastewater collection, treatment and disposal, electrical power supply and distribution, standby power supply, refrigeration, vehicular access and parking, landscaping and pedestrian bridge replacement.",
          },
          {
            image: USPS,
            subtitle: "United-States-Postal-Service",
            SEOTitle: "United States Postal Service",
            location: "Various Locations",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering Commissioning",
            descriptionsummary: "R&W has provided engineering services for over 50 USPS projects over the past 5 years.",
            description1: "Services included HVAC, plumbing and electrical design as well as site investigation with reports of the existing systems, identification of code deficient items, comparison of various HVAC alternatives with recommendations and energy analysis and cost estimates. Both energy and cost savings were compared against ASHRAE 90.1 design. R&W has also provided retro-commissioning of the HVAC system for some of the buildings.",
          },
        ],
      },
      {
        id: "healthcare",
        img: health,
        title: "Healthcare",
        subCategories: [
          {
            image: bendUrology,
            subtitle: "Bend-Urology-Clinic",
            SEOTitle: "Bend Urology Clinic",
            location: "Bend, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W Engineering completed both the Core & Shell and Tenant Improvement phases of this medical office building.",
            description1: "This building is a 21,000 square foot medical facility, housing 12,000 square foot of clinic area, office area, and lab areas and 8000 square feet of space devoted to ambulatory care. This facility houses offices, exam rooms, procedure rooms as well as two full surgery suites and recovery rooms. R&W provided mechanical and electrical design services. Design included HVAC, exhaust, medical gas piping, power, lighting emergency power, data, telephone and low voltage. R&W utilized a variety of variable and constant volume HVAC systems to meet the diverse needs of the users. Lighting and power was provided in a variety of ways.",
          },
          {
            image: CorvallisClinic,
            subtitle: "Corvallis-Clinic",
            SEOTitle: "Corvallis Clinic",
            location: "Corvallus, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "Auman Building: Provided Mechanical and Electrical design services for the renovation of all clinic areas of a 28,000 sq. ft. building.",
            description1: "The medical facility included administrative areas, mammography, ophthalmology, pediatrics, radiology, CT area, hearing lab, and behavioral health areas. Design services included HVAC, plumbing, electrical, fire protection, lighting, power and low voltage – data/communication design services.",
            description2: "Walnut Building: Provided Mechanical and Electrical design services for the TI of a 10,500 sq. ft. medical office building. Facility included two procedure rooms, X-ray area, exam rooms, offices and exercise therapy spaces. Design services included HVAC, plumbing, electrical, lighting, power and low voltage.",
            description3: "Asbury Building: Provided Mechanical and Electrical design services for the renovation of 2,000 sq. ft on the 1st floor, 2,000 sq. ft. on the 2nd floor and 9,000 sq. ft. on the 3rd floor. Renovated spaces included offices, exam rooms, CT area, Ultra Sound area, and laboratory spaces. Design services included HVAC, plumbing, electrical, fire protection, lighting, power and low voltage.",
          },
          {
            image: westHillsGastro,
            subtitle: "West-Hills-Gastroenterology",
            SEOTitle: "West Hills Gastroenterology",
            location: "Portland, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W provided HVAC, plumbing, medical gas, lighting, power, fire alarm, fire protection, nurse call, and security design for this 23,000 square foot tenant improvement for medical procedure area, exam rooms, admin area and office areas.",
            description1: "",
          },
          {
            image: willametteFallsCommons,
            subtitle: "Willamete-Falls-Commons-Medical-Office",
            SEOTitle: "Williamate Falls Commons Medical Office",
            location: "Canby, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W provided mechanical and electrical engineering services for the design of the HVAC, plumbing, fire protection, power, fire alarm, low voltage and lighting design for the 22,900 square foot, 2-story medical office shell building.",
            description1: "",
          },
        ],
      },
      {
        id: "Industrial",
        img: industrial,
        title: "Industrial",
        subCategories: [
          {
            image: lehighCement,
            subtitle: "Lehigh-Cement-Terminal",
            SEOTitle: "Lehigh Cement Terminal",
            location: "Port of Everett, Washington",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            service3: "Automation",
            descriptionsummary: "Owner's project was to convert an existing alumina ore import terminal for cement import.",
            description1: "The existing system consisted of a dockside mobile ship unloader, dock receiving system conveyors to an existing storage dome, and a dome reclaim system to a rail loading system. The new system improved existing dock receiving conveyors, improved and added dust collection equipment, provided major modifications to the existing storage dome to install an extensive aerated reclaim system, improvements and modifications to dome discharge equipment and reclaim conveyor, modifications and improvements to existing receiving bucket elevator to the existing rail, and replacement of existing rail loading storage bins with new bins with aeration and articulated delivery systems for cement loading of rail. In addition, the reclaim system was added to with additional transfer equipment to a completely new fully automated truck loading system with storage bins and truck scales for two lanes simultaneously. R&W provided electrical power systems design, overall plant automation including integration of multiple vendors and software development and provided compressed air system and piping design.",
          },
          {
            image: columbiaSteel,
            subtitle: "Columbia-Steel-Casting-Sand-Distribution-Mullor-Automation",
            SEOTitle: "Columbia Steel Casting, Sand Distribution Mullor Automation",
            location: "Port, Oregon",
            service1: "Electrical Engineering",
            service2: "Automation",
            descriptionsummary: "R&W worked with the plant process engineering to develop PLC automation upgrades to replace existing electro-mechanical sand mulling control equipment.",
            description1: "This equipment blends reclaimed sands with water and bonding agents to create molding sand for the casting operations. The system now incorporates reclaim sand temperature and/or moisture measurements to calculate water addition with each batch. Water addition is now performed with accurate magnetic flow metering to an accuracy of 0.1 gallons per batch. Mullors No. 2 and 4 were the first ones installed with the new PLC based automaton. Subsequently in 2009-2010 Mullors 1 and 3 were automated in a similar manner. However, Mullor No. 1 produces facing sand formulations and uses multiple sand sources for each batch. Therefore, this system was provided with a recipe based formula system to allow operators to create facing sand formulations and to be able to rapidly switch from one to another. All Mullor batching systems produce a final casting sand batch every 2-4 minutes depending on mulling time. All plant sand mulling operations are now fully automated with plant PLC's.",
          },
          {
            image: kochCarbonSulfur,
            subtitle: "Koch-Carbon-Sulfer-Transfer-Pads",
            SEOTitle: "Koch Carbon Sulfer Transfer Pads",
            location: "Corpus Christi, Texas",
            service1: "Electrical Engineering",
            service2: "Automation",
            descriptionsummary: "R&W provided electrical design services for Koch Carbon that included portable conveyors, radial stacker, truck wash and storage pond pumping systems, site lighting and a small modular MCC room.",
            description1: "The MCC room accommodates the truck unloader motor starter and control panel along with a PLC panel and the lighting panel. This MCC room also includes a lighting transformer and distribution panel. The electrical design consisted of pole mounted flood lighting, lighting controls, instrumentation, PLC and OIT programming.",
          },
          {
            image: malhuerLumber,
            subtitle: "Malheur-Lumber-Pellet/Briquette-Production-Plant",
            SEOTitle: "Malheur Lumber, Pellet/Briquette Production Plant",
            location: "John Day, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            service3: "Automation",
            descriptionsummary: "R&W was commissioned to assist with the electrical power, lighting, and automation systems of a new processing plant to produce wood pellets and briquettes for wood burning stoves and wood based water boilers.",
            description1: "This project had substantial ARRA funding and resulted in new jobs for the Central Oregon town of John Day. R&W developed and designed the entire power supply system design for all equipment including chip receiving, chip drying equipment, chip size reduction with grinders, final dry chip storage, reclaim conveyance to two briquette machines, a palletizing mill, provisions for a future pellet mill, and final pellet mill storage and truck loading system. R&W developed and designed a PLC based automation system for the entire plant. R&W provided all automation software development and performed all on-site start-up testing and commissioning. Project had a short time schedule and R&W assisted with the advance purchase of all major electrical equipment and automation equipment. As a result, with a start of design in March, the plant was built and operational by December of the same year.",
          },
          {
            image: tokaiCarbonFurnance,
            subtitle: "Tokai-Carbon-CVD-Furnace-4",
            SEOTitle: "Tokai Carbon CVD Furnace #4",
            location: "Hillsboro, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            service3: "Automation",
            descriptionsummary: "R&W provided design services for construction and installation of a large CVD Furnace for treating of large components.",
            description1: "Design was based on a unit originally constructed in Japan, duplicated in South Korea and this would be the third unit of this size in the world. Design was provided for expansion of plant facilities and electrical systems. A new electrical power service design was provided and new process water cooling system design was provided. The process water system was designed for capacity to support two (2) new purification furnaces that were installed in a secondary building at the site. The CVD vessel construction design was coordinated to provide certifications to meet U.S. requirements as a certified vessel. The CVD unit utilizes specialized high capacity electrical heating elements and R&W designed a custom bus-work supply system and coordinated measures to reduce electrical induction into structures. R&W assisted with the complete process system design including gas vaporization systems, gas delivery systems and full PLC automation of the CVD furnace operations.",
          },
        ],
      },
      {
        id: "leed",
        img: LEED,
        title: "LEED",
        subCategories: [
          {
            image: PWBMeterShop,
            subtitle: "Portland-Water-Buereau-Meter-Shop-Relocation:-LEED-(R)-Gold",
            SEOTitle: "Portland Water Buereau: Meter Shop Relocation: LEED - (R)- Gold",
            location: "Portland, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            service3: "Commissioning",
            service4: "Energy",
            descriptionsummary: "R&W provided design services for all general building HVAC, plumbing, power and lighting.",
            description1: "Project included a 12 KW grid tied photovoltaic system and a solar thermal system providing domestic hot water for the building. The design also included all piping and automation design services for construction of new large meter (3″-12″) test bench with flows ranging from ¼ GPM to 5000 GPM. The new meter testing facility includes load cell measurements of water calibration tanks for the small meter systems and a larger PLC based (Modicon) automated high capacity meter testing system. This latter system uses NBS trade certified Coriolis effect meters and a recycle water supply pumping system as a part of the first building for the City of Portland that attained LEED accreditation.",
          },
          {
            image: wuanaCredit,
            subtitle: "Wauna-Credit-Union-LEED-(R)-Silver",
            SEOTitle: "Wauna Credit Union: LEED (R) Silver",
            location: "Scappoose, Oregon",
            service1: "Electrical Engineering",
            service2: "Mechanical Engineering",
            service3: "Commissioning",
            service4: "Energy",
            descriptionsummary: "This project is a community credit union building of approximately 2,100 square feet.",
            description1: "Approximately 1,350 square feet of the building was a remodel of an existing building with the remainder being additions. R&W provided electrical, mechanical, plumbing, energy engineering and LEED services. In addition we assisted the Commissioning Agent in leading the LEED fundamental and enhanced commissioning services.",
          },
          {
            image: cheCultureCenterLEED,
            subtitle: "Chehalem-Cultural-Center-LEED-(R)-Silver",
            SEOTitle: "Chehalem Cultural Center: LEED (R) Silver",
            location: "Newberg, Oregon",
            service1: "Electrical Engineering",
            service2: "Mechanical Engineering",
            service3: "Commissioning",
            service4: "Energy",
            descriptionsummary: "Chehalem Park and Recreation District hired R&W Engineering to provide electrical and mechanical design services, LEED energy analysis, LEED services, and commissioning services for this community/cultural center pursuing LEED Silver certification.",
            description1: "This 2- story building originally served as an elementary school and this project involved converting it into a cultural center. R&W hired and worked closely with the commissioning agent to provide fundamental and enhanced commissioning to meet LEED's requirements. R&W has been providing mechanical and electrical engineering services for this project since it began in 2004. The project included the seismic upgrade, demolition of existing HVAC, plumbing and electrical systems and design for new HVAC, plumbing and electrical systems in a phased construction. Work has included public meetings with the park and recreation department to explain quality of existing systems and options for upgrade. This project uses a water source heat pump system, a high efficiency boiler and cooling tower, daylight lighting controls, occupancy sensors for lighting control, demand control ventilation, solar water heating, high efficiency condensing water heater and indirect lighting.",
          },
          {
            image: kcoffeeBeanInter,
            subtitle: "Coffee-bean-International-LEED-(R)-Silver",
            SEOTitle: "Coffee Bean International: LEED (R) Silver",
            location: "Portland, Oregon",
            service1: "Electrical Engineering",
            service2: "Mechanical Engineering",
            service3: "Commissioning",
            service4: "Energy",
            descriptionsummary: "This LEED® Silver Certified Tenant Improvement consisted of adding 17,500 square feet of new office space over two stories constructed inside an existing warehouse building.",
            description1: "The remaining 100,200 square feet of the empty warehouse space was converted primarily to manufacturing space used for coffee roasting, processing, flavoring and packaging. When they moved into their new facility near the PDX airport, they hired R&W Engineering to provide full Mechanical and Electrical Engineering services as well as the LEED Fundamental Commissioning for this project. The change of use required completely new energy efficient HVAC systems using rooftop units and variable air volume systems, larger electrical service, new energy efficient T-5 HO lighting in the warehouse and pendant direct/indirect in the offices, ultra low water use plumbing fixtures and many other sustainable design features. R&W provided energy modeling and fundamental commissioning services to help attain a LEED Silver rating.",
          },
          {
            image: youthFam,
            subtitle: "Youth-and-Family-Link-LEED-(R)-Certified",
            SEOTitle: "Youth and family link: LEED (R) Certified",
            location: "Longview, Washington",
            service1: "Electrical Engineering",
            service2: "Mechanical Engineering",
            service3: "Commissioning",
            service4: "Energy",
            descriptionsummary: "Youth and Family Link is a nonprofit organization that provides services to engage children and families, who struggle in home, school, or have been hospitalized due to mental health issues, towards positive resources.",
            description1: "R&W provided services to help achieve a LEED® Certified rating, as well as Electrical and Mechanical design and commissioning services. R&W completed HVAC, plumbing, lighting and power design for the addition and a new gymnasium and two classrooms, remodeled existing building entry, lobby, and restrooms. The lighting design that R&W provided for the classroom and gym saves energy effectively by using day lighting sensors. The use of Solatubes enabled the reduction of lighting, creating more efficiency. Natural ventilation is used for gymnasium cooling supported by high efficiency rooftop units. The classrooms are cooled using high efficiency split system heat pumps. All Plumbing fixtures are low flow saving over 30% of normal water usage. R&W assisted the contractor with LEED commissioning services which provided the ability to monitor the project, maximizing the efficiency to meet all State and local codes. R&W assisted in meeting grant requirements for state funding. R&W provided LEED consulting services including: building energy modeling, eco-charettes, meetings, etc.",
          },
        ],
      },
      {
        id: "municipal",
        img: municipal,
        title: "Municipal",
        subCategories: [
          {
            image: municipalReclamation,
            subtitle: "City-Of-Chehalis-Regional-Water-Reclamation",
            SEOTitle: "City Of Chehalis, Regional Water Reclamation",
            location: "Chehalis, Washington",
            service1: "Electrical Engineering",
            service2: "Mechanical Engineering",
            service3: "Commissioning",
            service4: "Automation", 
            service5: "Energy",
            descriptionsummary: "The City of Chehalis, WA constructed a new replacement waste-water treatment system for the entire community.",
            description1: "This will meet the requirement for discharges during the Chehalis River low-flow periods for the City to suspend discharges into the river. R&W's largest SCADA infrastructure project, a Rockwell PLC with Wonderware HMI system. The plant design uses an SBR treatment system with UV disinfection. Large capacity equalization-storage basins provide for flow equalization and transition between operating discharge modes. During low river flow conditions the effluent is routed via tertiary sand filtration and then delivered to a land disposal area with a Poplar Tree plantation on the other side of the river.",
            description2: "The overall plant design has provisions for a future 100% increase in the SBR treatment process. In addition the waste solids will be treated using a sludge pasteurization process to accommodate land disposal. Wastewater flows are delivered via newly upgraded main pump stations off-site from the plant.",
          },
          {
            image: bendWell,
            subtitle: "City-of-Bend-Outback-Well-6",
            SEOTitle: "City Of Blend: Outback Well #6",
            location: "Bend, Oregon",
            service1: "Electrical Engineering",
            descriptionsummary: "Design electrical service to serve one new deep well and two future deep wells for water supply to the City of Bend.",
            description1: "One new reservoir was added at the site with utilities designed to support two additional future reservoirs. Electrical design included utility supply for 300 HP deep well pumps, controls for local and remote pumps, and flow monitoring for the pipelines leaving the site.",
          },
          {
            image: jointWaterCommision,
            subtitle: "Joint-Water-Commission-Plant-Electrical-Evaluation",
            SEOTitle: "Joint Water Commission:, Plant Electrical Evaluation",
            location: "Forest Grove, Oregon",
            service1: "Electrical Engineering",
            descriptionsummary: "R&W Engineering was tasked with reviewing and assessing the condition of the components",
            description1: "of the electrical distribution system at the Spring Hill Pumping Plant and the Water Treatment Plant to recommend reliability and redundancy improvements.",
            description2: "As part of the assessment, system models were developed for the primary focus elements to run short-circuit and arc flash hazard studies.",
          },
          {
            image: seasidePetersonPointReservoir,
            subtitle: "City-of-Redmond-Reservoir-6",
            SEOTitle: "City of Redmond: Reservoir #6",
            location: "Redmond, Oregon",
            service1: "Mechanical Engineering",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W Engineering provided electrical and HVAC design services for a new well pump and booster pump building.",
            description1: "The building was designed to accommodate future pumping as the City of Redmond development growth requires. The well and booster pumping is provided with full standby power backup during utility outages to allow Redmond to continue providing water for domestic and fire. Our design also included electrical connections for two new reservoirs to monitor level, flow, and water quality.",
          },
          {
            image: redmonReservoir,
            subtitle: "City-of-Seaside-Peterson-Point-Reservoir",
            SEOTitle: "City Of Seaside: Peterson Point Reservoir",
            location: "Seaside, Oregon",
            service2: "Electrical Engineering",
            descriptionsummary: "R&W provided design for the upgrade to the existing PLC and control systems and development of a new SCADA system for the Peterson Point Reservoir.",
            description1: "R&W programmed the new PLC In the Raw Water Pump Station and revised the program in the existing plant PLC, as well as development of the software for the new HMI computer.",
          },
        ],
      },
    ];
    
    export default projects;