import { StaticImageData } from 'next/image';
import { MarkWirf, Covid19, tools, RNW, gregRobertson, harryreeder, CIDA100, balancingworkandfamily, orcascropped, fireflowtests, automation, cealingSquares, VRF, intern, troubleshooting, utilityCoordination, sistersmaintance, lessonCFD, LowHanging, cause, enginerd, humansnotnumbers, GreenEnergy } from '../blog/blogassets/blogassets';

export type BlogPost = {
  id: string;
  date: string;
  img: StaticImageData;
  title: string;
  SEOTitle: string;
  description: string;
  description2?: string;
  description3?: string;
  description4?: string;
  description5?: string;
  description6?: string;
  description7?: string;
  description8?: string;
  description9?: string;
  description10?: string;
  description11?: string;
  description12?: string;
  description13?: string;
  description14?: string;
  description15?: string;
  description16?: string;
  description17?: string;
  description18?: string;
  description19?: string;
  description20?: string;
  description21?: string;
  description22?: string;
  description23?: string;
  description24?: string;
  description25?: string;
  description26?: string;
  description27?: string;
  description28?: string;
  description29?: string;
  description30?: string;
  description31?: string;
  description32?: string;
  description33?: string;
  description34?: string;
  description35?: string;

};



export const BlogData: BlogPost[] = [
    
    {
        id: 'mark wirfs',
        date: "April 6, 2021",
        img: MarkWirf,
        title: "Owner-profile-Mark-Wirfs",
        SEOTitle: "Owner Profile: Mark Wirfs",
        description: "Founder of R&W Engineering, Mark Wirfs, began his career in the engineering industry while he was still a student at Oregon State University. He worked for one year in the engineering department of a plant as he got his engineering degree. In 1971, he graduated with this Bachelor of Science in Electrical Engineering, and thus began the path that would eventually lead him to start the R&W Engineering business.",
        description2: "Before he decided to study engineering, Mark considered becoming a musician. He has played the trombone since 4th grade. But he decided to pursue engineering because it was more lucrative. As a senior in high school, he also considered studying physics and interviewed with a physics professor. Ultimately, he chose engineering because he liked that it was less theoretical and would allow him to build things.",
        description3: "After graduation, he started working for a large firm. But, unhappy with his level of advancement there, he changed jobs and went to a smaller firm. In need of something more, he then started looking for another opportunity. That was when he ran into Harry Reeder in an elevator. They struck up a conversation and several months later, they founded R&W Engineering.",
        description4: "When asked what he thought R&W’s greatest challenges have been overall, he said, “Staying in business during economic slowdown. And getting through slow periods of design and construction.” He said there were periods where they had to reduce staff, and that it became necessary to recognize that before real economic problems really hit.",
        description5: "He said during those times, they worked diligently to find new work. It was at this point that they developed a business of working with municipal clients, particularly water and wastewater treatment plants. “Therefore, water and wastewater projects allowed us to grow and find new avenues for work,” said Mark.",
        description6: "When asked what makes R&W successful, he said, “The people have been successful. As we expanded, we made sure to find good people. This really is a people’s business.” Wirfs said that he particularly enjoyed his association with great engineers and designers over the years. Involvement with so many different industries as well as the National Electrical Code (which he participated in as a member to write national electrical codes) meant he, “got to work with a great bunch of people.” R&W values its community, and it is clear this begins with our leadership.",
        description7: "Thinking back over the decades of projects he has worked on, Mark said he remembers several that were particularly interesting. “[R&W] was involved with a printed circuit board chemical treatment facility.” He said that the Chehalis wastewater treatment plant was a project that stood out in his mind. “It’s not often a city replaces a whole plant, and Chehalis did.” When asked what made these projects so unique, he said, “It was the opportunity to work in different environments, and the challenge to help contractors design and procure equipment.”",
        description8: "Outside of work, Mark is very active. He loves to play golf and does so quite a bit. And while he is not a professional musician, he still plays the trombone. He has even been in several different bands and symphonies at different times in his life.",
        description9: "Like so many of our leaders, Mark Wirfs’ dedication to R&W Engineering is one of the reasons we have thrived for as long as we have. With founders like him who prove their commitment to the company and its workers time and time again, we can trust the atmosphere built in this company is one intended to help us all succeed.",
    },

    {
        id: 'covid-19difficulties',
        date: "March 5, 2021",
        img: Covid19,
        title: "Adapting-to-Covid-19-Difficulties",
        SEOTitle: "Adapting to Covid-19 Difficulties",
        description: "Since Oregon’s Shelter-In-Place orders were given, R&W Engineering’s employees have been working remotely. Our fantastic leadership and IT personnel have worked hard to ensure we can do our jobs effectively from home. And while this change presents challenges, adapting to other difficulties because of Covid-19 has also been an on-going process.",
        description2: "There are many challenges we each face as remote workers. For some, the biggest challenge is working from home while their children learn online. This means parents must juggle meal prep, snacks, and helping kids with their work, while also getting their own work done. Some parents try to mitigate this by planning meals and snacks the night before. “We have a menu for the week for lunches, so [the kids] know what they are having. Of course, there are times they want something different than the menu, but they are reminded that this is not a restaurant,” one parent said. Menu and meal prep can be one way to reduce the stress of at-home work and learning.",
        description3: "As for online learning, parents say that some kids do well, while others struggle. Older children can keep themselves on task. But younger children have struggled in the transition. “There are times I have my youngest read books or listen to stories while I work, and we complete his independent assignments when I have a break, am on lunch, or after work.  Each day is different, and we adjust as we go,” said one parent. What a great coping mechanism for these uncertain times, too: remembering that each day is different and it’s okay to adjust as we go.",
        description4: "Other quarantine challenges affect students, parents, teachers, and employees alike. The lack of social interaction can make a negative impact on all of us. Being in isolation for long periods when we’re used to having wide access to family, friends, restaurants, movie theaters, and other people/places, definitely wears on all of us. Many of us are used to being involved in social activities like play dates, softball or other group sports, summer camp, musical festivals, church functions, college, or other learning programs, etc. Being disconnected from all of that is a hard adjustment. “We really are social creatures,” an employee said.",
        description5: "And even though we have things like Zoom, Google Hangouts, FaceTime, and other technologies that allow us to socialize while maintaining distance, there are still other things we miss. Physical affection, being in someone else’s presence, and even being outside of our own home are important to our mental and emotional health. And while our employees have found ways of making this work (socially distancing outside with family and friends, for instance), it is still a struggle.",
        description6: "Not all challenges are directly related to the isolation of quarantine. Some employees say that one of their biggest challenges is managing technology. Learning new tools and utilizing them efficiently, and then switching between programs, can be difficult. Included in this is also the use of different forms of communication. All R&W employees have Microsoft Teams and Outlook on our phones now to increase the likelihood that we will receive any emails and messages that come through, even when not at our computers. “While these tools seem to work well for the most part, it is sometimes difficult to ignore a notification or string of notifications on my non-working hours. It can also be distracting when a conversation via a Team’s chat is taking place and the notifications keep coming.” Working remotely means managing through technological adjustments, and there are times when this is harder than it seems.",
        description7: "Many, if not all, of R&W employees expressed that they miss the social connection of in-person conversations while working. “I miss not being able to see or catch up with co-workers beyond our weekly video chats – larger group conversations make it harder to find out what’s going on with everyone.” Our leadership and management personnel have done a fantastic job of keeping everyone connected. We have a weekly Teams video chat where anyone who wants to can catch up. Our Halloween Party was also virtual last year, and included our Pumpkin Carving and Costume Contests, as well as Halloween Trivia. All of these we would do in-office. “I am typically a social butterfly but feel like a moth lately. I HATE MOTHS!” one employee said.",
        description8: "But we’re also adaptable. Making the most of situations is a healthy way of coping with the uncertain and unexpected. For this employee, having a small social bubble has made all the difference. “When the weather was better, we would do a lot of things outside with family and friends, keeping distance. We also have lots of video calls with family and friends.” Their family has done some online escape room/mystery solving games together, alleviating some of the monotony. Prioritizing virtual socialization is something I think all of us in quarantine need to remember to do. Knowing that there are so many ways to connect to people is helpful.",
        description9: "As we get closer to the one-year mark of working remotely, we’re reminded just how much we’ve endured. And while things continue to be difficult, it’s important to see the little victories. Finding ways of staying connected is a victory. Communicating our struggles is a victory. We hope as 2021 continues to progress through the Covid struggle, you will celebrate your little victories as we celebrate ours.",
    },

    {
        id: 'quarantineprojects',
        date: "November 5, 2020",
        img: tools,
        title: "Our Quarantine Projects",
        SEOTitle: "Our Quarantine Projects",
        description: "As we pass into autumn, it’s clear just how much our lives have changed since the global pandemic hit the United States. Amusement parks closed, cancelling many summer plans. State and national parks restricted access, making hiking, BBQs, and camping difficult. And while we have begun to settle into something resembling a new normal, we see how different things are than they were a year ago.",
        description2: "But it’s not all gloomy. R&W employees have kept up to date on a long list of quarantine projects. We have been busy with building and remodel projects, home schooling projects for those with kids, and other activities for personal enjoyment. Being quarantined and away from the office has meant adjusting to difficulties. But it also means more creativity in the ways we entertain ourselves.",
        description3: "Our at-home quarantine projects span a wide array of types and levels of complication. One member of the R&W family has finished a long list of projects, two of which included constructing a house for the well on his property and clearing away the underbrush near the fence around his property. Of all the projects, he listed the well house as his favorite: “[It] was built using metal [for the] siding and roof. I have done some metal roofing but never siding, so this was a fun challenge to figure out all of the connections, overhangs, and trim to make it weather-tight and look nice.”",
        description4: "The other large project he completed was clearing away the brush from around his property to make walking trails: “Clearing brush for the trails is a constant, never ending battle. I have let it go for too long and now it gives me a productive way to get exercise. It’s also a great stress reliever. There are some areas around our fence line that I have not been able to get into for more than 20 years.” Completing components of a project 20 years in the making! That is next-level productivity! This project began, he said, because his wife mentioned she wanted to see the other side of the property from their back deck. And now she can. You can see the before and after pictures below.",
        description5: "What is interesting about these projects is how diverse they are in terms of what they accomplish. Some projects, like the two just mentioned, are more on the productive side, using quarantine to clean up, remodel, build, and finish up tasks needing to be completed. Other projects have been more on the fun side, taking time to invest in new and old hobbies, and spending time with family. Our next featured projects fall into this category.",
        description6: "Another staff member bought a metal detector and spends time with his daughter every week looking for loose change and other treasures. When asked what prompted this project, he said: “My daughter was at her grandparent’s house for the day and brought home treasures from their backyard…I saw her excitement…and it was a no brainer. Even though she only brought home trash, to her it was buried treasure.” 2 to 3 times each week, they take the metal detector to neighborhood parks, schools, and to the beach to search the sand for buried items that have been left behind and forgotten.",
        description7: "He said they mostly find loose change, primarily pennies. But they have also found match box cars, nails, pop cans, keys, and a couple of bullets. They even found a ring and a charm bracelet, which his daughter loves to wear and are her favorite found items. And he is most excited by the silver nickel and 1954 half-dollar they found. They have been saving all the loose change to show people. “The best part” he said, “is hanging with the kid, for sure!” They usually go out for a couple of hours at a time. Not only is there great bonding between the two of them, but it gets them out of doors in a way that is safe and allows exercise.",
        description8: "Some of our quarantine projects have been simple, but helpful. One staff member built a deck vision screen to maintain privacy as the lot next to their house was sold and was being divided. He said they built it “…using reclaimed fence wood and metal from auto ramps and other materials. Along with some welding and ingenuity, we constructed our 16ft long and 6ft high vision screen.” Maintaining privacy during a time when so many people are staying home is becoming more essential.",
        description9: "Another staff member has been painting. She began in junior high. When asked how she came to be interested in painting, she said, “Watercolors. I did a beautiful watercolor of a vase of roses in 7th grade and have been hooked ever since.” She primarily works in acrylics since it’s what she has. She said she tried oils over this last weekend and learned it’s not her medium.",
        description12: "She has also taken up relearning to speak French. It was something she started in high school. She said she’s been working since May to expand her knowledge. When asked what her long term plans are for painting and French, she said, “I think with painting I would love to make gifts for people…As for French, it’s just to pass the time.” She did recall once when she was 22 and working at Applebees, a large group of primarily French-speaking customers came into the restaurant. She was the only one working who spoke any French. She was able to help them order. “They were very polite and left a great tip.”",
        description13: "And lastly, another member has been remodeling sections of his home with his wife. They’ve completed quarantine projects, including the extension of their kitchen island to make room for breakfast/prep area, adding a leveled paving stone walkway from the front of the yard, painting their bedroom, and refurbishing a small floor cabinet to hold towels and other toiletries. When asked which project was the hardest, he said, “The island extension by far. It was a lot of standalone kitchen parts…that we put together to make the full extension. [It meant] making sure they all aligned properly and matched…cutting pieces to better lengths, sanding, painting, matching style…” This kitchen island project was also his favorite, he said, because it turned out really well and they use it every day.",
        description14: "These are only a few of our at-home projects. I’m sure there will be even more as we go into 2021. And while this year has not turned out the way we thought it would, it’s great to see some of the things we still accomplished. Because this is evidence of some of what makes R&W such a fantastic company. We are full of problem solvers, devoted workers, creative thinkers, and strong leaders. As a company and as individuals, we go above and beyond. Even during a global pandemic when stakes are high and so much is uncertain, we still find ways to be productive, both on the job and at home.",
    },

    {
        id: 'harryreeder',
        date: "June 21, 2019",
        img: harryreeder,
        title: "Owner-Profile-Harry-Reeder",
        SEOTitle: "Owner Profile Harry Reeder",
        description: "Author: Janel Brubaker",
        description2: "R&W Engineering has seen some incredible milestones in the last couple of months. From reaching 100 projects with CIDA to celebrating our 41st anniversary, 2019 has already been a fantastic year. As we reflect on all we’ve accomplished, it’s clear that none of it would have been possible if not for our founders. With this post we’d like to honor one of them, Harry Reeder.",
        description3: "Mr. Reeder has been in the engineering and construction field for 64 years. He graduated from Oregon State University with a B.S. in Mechanical Engineering. He also has an M.S. in Mechanical Engineering. When asked why he chose such a degree, Harry said, “Because I loved airplanes and wanted to work in the airplane industry.” And he did! Mr. Reeder worked for Boeing for 11 years before he left and worked another 11 years as a mechanical engineer for a consulting engineering firm. “The big changes in my life have occurred in cycles of eleven years,” he said.",
        description4: "One of the most challenging aspects of starting R&W, he said, was the finances. Finding clients so they could make enough to stay open was a concern for the first two years. “So we just had to keep on working,” Mr. Reeder said. Because of this, he and the co-founder, Mark Wirfs, decided to focus the company on electrical engineering, instrumentation, and control systems. The Portland area was already saturated with mechanical engineering firms and other engineering needs were given less attention. Mr. Reeder and Mr. Wirfs saw in that an opportunity to meet a need in the area and bring in more clients simultaneously.",
        description5: "As they focused their initial efforts on establishing themselves as an electrical engineering, instrumentation, and control systems firm, they also worked hard to launch a mechanical engineering side. These different services allowed them to generate a diverse list of clients who could come to R&W for a variety of engineering needs. Because of this, the company became financially solid after two years and by the five-year mark, had an excellent client list.",
        description6: "“The most rewarding part of being an owner of R&W has been watching it grow and watching the employees grow,” said Mr. Reeder. He described R&W as being a culture of honesty filled with respectable people. “I always tried to hire people smarter than me,” he said. “So I think we’ve built a company we can be proud of.” Mr. Reeder has been a pillar of strength for R&W. His leadership, his unwavering dedication to the company, the employees, and the clients, and his love for the industry are part of what has made R&W so successful.",
        description7: "Harry Reeder loves to play golf and he’s an Elder in his church. Mr. Reeder was very active in the American Society of Mechanical Engineering where he served in several positions, including as member of the Governing Board. He has travelled for a lot of different jobs, relocating to several states, though Oregon has always called him back. Also, he was the 30th President of The Consulting Engineers of Oregon (now called the American Council of Engineering Companies of Oregon). Mr. Reeder likes to read historical novels and is currently working his way through Churchill. Harry played football, basketball, and baseball in high school. When he worked for Boeing, he played in their company’s softball league.",
        description8: "R&W appreciates all that Mr. Robertson has done for us. We’re lucky to have him on our team!",
        description9: "We love and respect him as a person and for all he’s done for R&W, and find great value that he still visits the office and mentors us in his free time. Thank you, Harry!"
    },

    {
        id: '100project',
        date: "April 9, 2019",
        img: CIDA100,
        title: "CIDA-Celebrating-the-100th-Project",
        SEOTitle: "CIDA Celebrating the 100th Project",
        description: "Author: Janel Brubaker",
        description2: "Inspiration is often an undervalued component to office life. Some workplaces focus on other aspects of running an office, like time management and safety. And understandably so; these are important to the success and efficiency of a workplace. But this also means that some aspects of what drives a work environment can be overlooked. When companies emphasize the importance of lasting professional relationships, the results can be astounding.",
        description3: "One company that R&W has worked with that meets this standard is CIDA, Inc. They’re a company R&W has enjoyed working alongside for over 25 years. The positive interactions between our respective team members has built an environment of trust and respect. Because of this, R&W has worked with CIDA on 100 different projects. This is an exciting prospect that reflects R&W’s dedication to building lasting relationships and also speaks to the type of relationship we have with CIDA.",
        description4: "One of our team members said his favorite part of working with them is the positive professional relationship between our two firms: “There’s more of an understanding of people, in terms of deadlines and people’s personal time. Everyone still has a life outside of the office.” When asked about the importance of R&W’s professional relationship with CIDA, he said, “It’s very important. Without them, I would not have been referred on other projects.” He continued, “Projects are not always perfect. They have their own oddities. CIDA understands that and the team works together to resolve problems in a timely manner.” Understanding the perspectives of employees, clients, and contractors is exactly the kind of professionalism that inspires loyalty. It also fosters strong connections between not only a company and their clients, but also a company and others they may work with.",
        description5: "In 2017, CIDA was recognized as one of the top 100 best companies to work for in Oregon. Companies that are good to work for are also often the companies that are good to work with. Another member of our team said of his favorite part of working with CIDA, “It’s the people. R&W’s vision is Building Lasting Relationships, and with the team at CIDA this has been easy. No matter who is assigned to projects at either company, we work well together and have mutual respect that makes projects fun and successful.” He continued, “…CIDA is a group of people that you know enjoy their work…and respect those they work with. Knowing my input is valued makes CIDA a great partner.” So, fostering positive professional relationships is a key inspirational tool.",
        description6: "Reaching the benchmark of 100 projects with CIDA is exciting for us at R&W. To have the kind of professional affiliation with a company where our team members enjoy interacting with their team members, even when stress is high, is a tremendous thing. It’s also precisely what has established the trust and respect that exists between our respective companies. And that trust and respect are the foundation of the rapport we’ve built over the last 25 years.",
        description7: "Attitude is another way that companies can inspire. It effects the daily life of the office as well as the continued relationships between a company and its clients. When asked about the 100 projects R&W has worked on with CIDA, a team member said, “This number indicates two firms that are more focused on getting good projects and doing the best quality work without allowing ego or territory to ruin the final product.” He continued, “Not only does R&W work for CIDA, but when appropriate, CIDA works for R&W. This sharing of the lead role to make a team that best serves the product and the client is telling and paints a picture of our relationship.”",
        description8: "The values, cultures, and attitudes of a company stem from its leadership. Owners and managers who emphasize the importance of professional relationships will likely create a working atmosphere that also emphasizes those relationships. Another member of R&W’s team said of her experience with CIDA, “There’s a comradery between our companies that has created great relationships and positive interactions. CIDA is the client you enjoy calling, and that makes jobs flow smoothly. It opens channels of efficient communication. There’s a greater feeling of being part of a team and cooperating toward the same goal.” She also said that, in her experience, these values are applied to every interaction she’s had with CIDA, regardless of whom she interacts with. This kind of inspiration builds professional success and establishes environments the clients and contractors enjoy being a part of.",
        description9: "Inspiration comes in many forms and through endless mediums. CIDA is an inspiring company for many reasons, some of which have been discussed here. What stands out is the positivity of their interactions with R&W. From being friendly and communicative to understanding the oddities of each job, CIDA has impacted R&W in positive ways. To see our firm reach 100 projects with CIDA is inspiring and serves to remind us that cultivating positive professional relationships is a worthwhile endeavor.",
        description10: "Here’s to 100 jobs with CIDA and many more to come!"
    },

    {
        id: 'balancingworkfamily',
        date: "January 5, 2018",
        img: balancingworkandfamily,
        title: "Balancing-Work-&-Family-Can-it-be-done?",
        SEOTitle: "Balancing Work & Family - Can it be done?",
        description: "Author: Heidi Speer",
        description2: "The task of balancing your work-life with your personal-life can be daunting, and in some cases, it can result in one of those two sides, losing. So which do you sacrifice: Work or Family?",
        description3: "For me neither was an option. Which was why “who” I worked for was so important when it came time to commit to a permanent position.",
        description4: "I had spent three years in that precarious position of contract employee, where your income was only guaranteed for a short amount of time. As a single parent that caused more than a few sleepless nights. I was eager for the stability that a permanent position offered, but I was worried what a permanent position might cost me when it came to my young child.",
        description6: "It was always the most heart pounding moment of a job interview. Bringing up the fact that I was a single parent to a 5-year-old and asking how a potential employer felt about the inevitable sick child phone call I’d get from the school that would cause me to leave work suddenly. There was the chance that your employer would appear to be sympathetic and understanding of your situation during the interview, however, in reality, if your child called you away from work more than two times it would actively start to affect how your employer treated you.",
        description7: "When R&W informed me that they were a “family first” company, I was relieved but knew to take all comments with a grain of salt, realizing that each company had their own definition of the phrase.",
        description8: "I’m happy to say that almost 12 years later, R&W is still true to their word. Whether you, a child or a pet is fighting an illness. If you must leave early for soccer practice, a school production or an anniversary dinner; management and co-workers are understanding. Flexible hours are available to help make-up missed time, and remotely accessing your work computer from home to keep on top of projects, helps relieve any stress someone may have for being away from their work obligations. It creates a balance that can be hard to achieve.",
        description9: "Finding a company that understands and accepts that an employee has responsibilities that lay outside the office, is important. Being a part of a company that believes that, and proves their belief every day creates a loyal work force that will give 110%, knowing that their company will support them in return.",
        
    },

    {
        id: 'exploreoregon',
        date: "December 2, 2016",
        img: automation,
        title: "Exploring-Oregon",
        SEOTitle: "Exploring Oregon",
        description: "Author: Tonya Minnick",
        description2: "Growing up in Nampa, Idaho near Boise (boy-see to the natives), and being a young single parent, I never got the opportunity to explore outside my boundaries. (Un)fortunately for me, the company I had been working at for the last couple years, decided to downsize starting with the newest employees in my department. No notice, just took my key card and booted me. Coworkers were nearly in tears as they lost two people that day and we were already working fifty hours a week. So, I saturated the market with my resume.",
        description3: "My interviews went great but Idaho isn’t known for fair wages. I continued to get interest at wages lower than what my unemployment checks were already supplying. Then the out of state calls started coming. North Dakota had a great offer, but I wasn’t interested in living there.  Seattle would be a nice place to live but who can survive in Seattle on the, twenty dollars per hour, offer I received?  This continued to discourage me.  Then I got a call from Volt Workforce saying they had an opportunity in Beaverton.  “Where is Beaverton?” I asked. “The home of Nike.” *silence* “Near Portland Oregon.” “Oh” I replied. “Sure, I’ll come out for an interview.”  Two days later I was in my car headed to a town full of Beavers.  Ten days after that, I was in that same little Saturn loaded to the brim with as much as I could pack into it. This included an air mattress, a relentlessly howling cat, and a little dog that insisted on riding atop the immense pile of precious necessities.",
        description4: "When I got here I had very little and was extremely nervous, as this was my first big adventure. Luckily the apartment I managed to get at the last minute, worked out wonderfully and was near work. Right away I noticed people were willing to help with my situation. I was given furniture, dishes, advice, etc.  These items came from, co-workers, new friends, one old friend that happened to be in the area, and a plethora of strangers. In what seemed like a very short time and only about five hundred dollars later, I had my apartment in a livable condition. I even had a real bed. And I was starting to make more friends that I could explore Oregon with.",
        description6: "Since getting settled in, I have taken many a trip to the coast and watched the gray whales and was able to witness some pretty spectacular breaches. While I had seen the Oregon Coast before, I never had the time to just relax and take it all in. Nor had I ever seen a whale in its natural habitat. Now I can go every weekend if I feel the need, and spend hours just looking out into the vast horizon. I finally experienced one of the most exhilarating moments of my life when I saw the tails of two Orca swimming toward the deep from Cannon Beach.  Did I mention that as a teen I had planned to attend OSU to become a marine biologist and study the Orca? Unfortunately, only the Jacque Cousteau’s of the world make a living sailing the seas and widening minds. But to see the multitudes of gray whales and then my Orca sighting, I was finally home.",
        description7: "While the sea side is my favorite Oregon location, I have found several other exciting places. The Tualatin Hills Nature Park is one of my favorite locations. It is chalk full of little critters and it’s a beautiful place to get your daily 10,000 steps in. Apparently, there are deer hiding in there too, but I have yet to find them. I personally have found, owls, bunnies, squirrels, toads, lizards, slugs, and a plethora of birds. It’s only one of many available trials in the area. Including the lovely Fanno Creek Trail. I have seen several great blue herons in the creek. Multnomah falls is also amazing. I have been up on the bridge but have not explored the higher trails. It’s a gorgeous natural waterfall with a manmade bridge to get us closer to nature. Oxbow park is also a wonderful place to visit.  I love the river, as it reminds me of the parts of Idaho I tend to miss on occasion. The self-titled little town at the base of Mount Hood also reminds me of the little Idaho town, of Marsing. The orchards and vineyards here are breathtaking in the fall. The little lodge at the base of the mountain was quaint but the road to the peak was closed due to snow, when I went. I can’t wait for next summer to explore some more.",
        description8: "The food scene is also spectacular here. I have discovered several scrumptious locations for tasty goodies.  I know Voodoo Donuts is a landmark but I’m in love with Beaverton Bakery.  I also found Mizumi Buffet, some delectable Chinese style seafood in a nice sized buffet.  Then all the noodle options to choose from at various places. I also love Mod Pizza, as they are like the super subway style pizza palace, with marion-blackberry lemonade that is amazing.  Portland Saturday Market with all the lovely food cart options, food pods as far as the eye can see, in downtown Portland and strewn about all the outlaying cities. My favorite Mexican food is in Vancouver (I know, not in Oregon), Taqueria El Antojo. They have the best tortilla soup and Mexican juices ever! This is accounting for the fact that Nampa has a heavy Hispanic population. There are also plenty of health conscious, yet delicious marvels to be found. Sweet Tomatoes is a nice healthy buffet. Just don’t overload on salad and soup. I am still hunting for my favorite places. It could take me years to find the best of the best. I am however, up for the challenge.",
        description9: "I am sure there are a multitude of Oregonian things I haven’t tried. I know there are several things on my list to explore. I am always eager for suggestions.  It would be awesome if some of you would leave some of your favorite places in the comments below. Hint, hint. Maybe you’ll feel the need to try a new place that I happened to find and mention here. I just want to say, I am so thankful to have found a company to work for, where my coworkers are also my friends. It was a leap of faith that brought me here and I am so glad I took that leap. I have found people I can count on if need be, in this new little family. This new adventure has definitely been a positive move. Of course, I miss aspects of Idaho, with friends and family at the top of the list. But, I feel like I belong here. I would like to thank each of you all for that.",
    },
    
    {

    
    id: 'fireflowtests',
    date: "August 17, 2016",
    img: fireflowtests,
    title: "Fire-Flow-Tests-How-&-Why",
    SEOTitle: "Fire Flow Tests, How & Why?",
    description: "Fire Flow Tests, also known as Hydrant Flow Tests can be performed for several different reasons.",
    description2: "Why?:In general, fire flow tests are conducted on fire hydrants to determine the water availability.There are multiple reasons why a flow test could need to be performed, below is a list of several of these reasons",
    description3: "To determine water availability in planning for firefighting activities.",
    description4: "To determine water availability for the design of fire sprinkler systems.",
    description5: "To determine water availability for the design of domestic water systems.",
    description6: "To evaluate development of water main extensions.",
    description7: "To evaluate system improvements and replacements.",
    description8: "To determine the general condition of the water distribution system by detecting closed valves.",
    description9: "Fire flow testing produces accurate water data which can be used for various purposes. Fire Fighting Agencies use this water data for training, planning and marking hydrants. This water data is also used for water system planning and design. Municipalities also use the water data to simulate high flow conditions, to determine pressure and flow-producing capabilities of the water distribution system and for calibration of hydraulic models.",
    description10: "How?:How often do Fire Flow Tests need to be performed on hydrants?",
    description11: "AWWA recommends flow testing all areas at least every 10 years (AWWA M17, chapter 6).",
    description12: "NFPA requires flow testing of underground and exposed piping at least once every 5 years (NFPA 25, Table 7.1.1.2, 2014).",
    description13: "How are Fire Flow Tests performed? There are two types of Fire Flow Tests:",
    description14: "Main Capacity Test determines the water supply availability in the water main. If you are designing a fire sprinkler system, use this test (residual hydrant + separate downstream flow hydrant).",
    description15: "Hydrant Capacity Test determines the flow-rate available from the hydrant and if it will deliver in a fire emergency situation. If you are performing fire flow tests of hydrants, use this test (residual hydrant and flow hydrant are the same one).",    
    description16: "For the purpose of this Blog we will only discuss how to perform a Main Capacity Flow Test, which is the two hydrant flow test. A Main Capacity Test evaluates the water supply of the fire main at the location of the test hydrant. The information derived from this test is used by city planners and contractors to consider the water supply for general use and fire sprinkler systems.",    
    description17: "Setup: At the test hydrant (pressure hydrant, static/residual hydrant):", 
    description18: "Attach gauge cap to test hydrant. Tighten all other caps.", 
    description19: "Open test hydrant, vent air from hydrant body through the valve on the gauge cap assembly. Close it when air is vented.",    
    description20: "Conduct the test",
    description21: "Record static pressure reading from gauge cap.",
    description22: "Slowly open hydrant using the gate valve to purge air from the hydrant. When hydrant is full of water, open gate valve to desired flow-rate (usually full open)",
    description23: "When the flow-rate stabilizes,",
    description24: "Record nozzle pressure from the remote reader.",
    description25: "and at the same moment",
    description26: "At the test hydrant",
    description27: "Record the residual pressure reading from the gauge cap.",
    description28: "At the test hydrant",
    description29: "Record the residual pressure reading from the gauge cap.",
    description30: "At this point, the test is complete.",
    description31: "Slowly close gate valve on flow hydrant, then close the hydrant. Remove test equipment from hydrant. Replace and tighten cap. If the hydrant is a dry barrel type, note that water drains properly from the hydrant.",
    description32: "Record the number of minutes that water was flowing. This can be used to account for the amount of water used during the flow test.",
    description33: "At the test hydrant",
    description34: "Close the hydrant. Remove gauge cap and replace hydrant cap. If the hydrant is a dry barrel type, note that water drains properly from the hydrant.",
    description35: "Now you know the How & Why of Fire Flow Tests a valuable tool in the engineer’s arsenal."
},
    

{
    id: 'automatingredundanttasks',
    date: "January 4, 2016",
    img: automation,
    title: "Automating Redundant Tasks",
    SEOTitle: "Automating-Redundant-Tasks",
    description: "As technology continues to advance automating has increasingly become a more common, widespread practice in all disciplines and industries to increase productivity, efficiency, and quality. The definition states that “Automation is the creation of technology to monitor and control a process, system, or apparatus.”[1] In another perspective, it is “The process of using computers and/or machines to do work that may have previously been done by humans.” [2] The applications can be anything from a simple redundant task and range to tasks so technologically advanced that they can’t possibly be done by humans. The programmable logic controller is the most common device used in industrial applications to complete many complex tasks.",
    description2: "The Programmable Logic Controller (PLC) is a digital computer that is programmed to control electromechanical processes such as robots, assembly lines, machines, temperature control processes, and other manufacturing processes [4]. Its major advantages include compact size, relatively low cost, and easily programmability. Due to its small size, a control enclosure size is significantly reduced and it requires less wiring compared to its now seemingly prehistoric predecessor, the hardwire relay control panel.  The PLC is programed using a language called ladder logic and is one of the most common languages used amongst PLC manufacturers. Therefore, any PLC can easily be programmed by a qualified professional. Adding to the advantages, the smaller size and easy programmability of the PLC significantly reduces the cost of a control panel and troubleshooting time. With the invention of the PLC, there have come many advancements in Automation, however there are disadvantages as well.",
    description3: "Some advantages of automation includes higher volume production, increased efficiency, less human error, reduced cost and a higher quality of products [3]. Some disadvantages includes a large initial investment, an increase in unemployment, and less versatility [3]. At a glance, it may seem the advantages outweigh the disadvantages, however depending on the processes, not all automation is advantageous. Regarding a smaller company, the large initial investment and relatively small volume production may not be beneficial at all.  Whereas larger companies with much more competition, it may be more advantageous to automate processes to achieve a competitive advantage. As automation is becoming more common in manufacturing processes, it is also being applied in other fields such as transportation, home and office as well.",
    description4: "A PLC is a particular category of computer used to control most industrial processes and has become synonymous with automation. However, automation has become more than simply a PLC controlling a manufacturing processes. A cell phone or car are both varying options of an automation tool. Without automation, it would not be possible to simply dial a phone number and talk to someone hundreds or thousands of miles away. Without a programmable computer in your car, it would not be possible to precisely control the speed of your car, or simply align the car in a straight line for that matter. A computer is used in virtually all office spaces today. The use of this technology aids in eliminating and reducing redundant tasks and manual processes, which in turn, improves productivity and efficiency in the workplace.",
    description6: "A question to ponder is what other everyday objects can be automated or haven’t yet been automated thus far? Is it beneficial and cost effective for a company to invest in automation?",
    description7: "References:",
    description8: "https://www.isa.org/about-isa/what-is-automation/",
    description9: "http://www.seartec.co.za/office-automation-4-things-every-it-manager-needs-to-know",
    description10: "http://www.vista-industrial.com/blog/advantages-and-disadvantages-of-automation-in-manufacturing/",
    description11: "https://en.wikipedia.org/wiki/Programmable_logic_controller",
},

{
    id: 'homelighting',
    date: "November 13, 2015",
    img: automation,
    title: "Is-your-home-lighting-causing-you-unnecessary-stress?",
    SEOTitle: "Is your home lighting causing you unnecessary stress?",
    description: "Lamp Colors for the Home",
    description2:  "It is often difficult for the average person to know what is happening in the world of lighting technology and the advancements that have been made to improve their environment.  With so many other questions and concerns occupying their daily thoughts and time, not much effort is put into considering different lighting strategies that can better their environment. What many consumers fail to understand is that inadequate lamp quality can cause unnecessary stress.  There are several spectrums that can be identified on the lamp packaging to aid in your search for which lamp best suit your needs.",
    description3: "What is Color Temperature?",
    description4: "Color temperature is conventionally stated in the unit of absolute temperature, in Kelvin, having the unit symbol K. The color temperature of a light source is the temperature of an ideal black-body radiator that radiates light of a comparable hue to that of a light source.  Black-body radiator test creates the base color for color temperature light that will be omitted from a lamp source.  The color temperature depicted on a line ranges from reddish/orange to yellow, and to more or less, white to blueish white.",
    description6: "Color Temperature",
    description7: "Within the home, the lamps you will find most often are generally incandescent bulbs, compact fluorescents, MR16’s, halogen and LED lamps.  As well as within the home, you may also have lamps on the exterior of the house in the form of metal halide, high pressure sodium or mercury vapor.",
    description8: "Most commonly found are lamps with color temperatures of 2700K, 3000K, 3500K, 4100K and 5000K. It isn’t as common, but you may find other color temperatures depending on the lamp manufacturer.",
    description9: "The lowest color temperature is 2700K and its lamp appears reddish and is a warm color.  Incandescent lamps are 2700K and are the best light temperature to be around while relaxing and prior to going to bed because of the warm soft hue.",
    description10: "The color temperature of 3000K to 3500K are a comfortable light range for indoor activities.  The light appears to be a whiter light and colors are more vivid.  These characteristics, in my opinion, are what makes them the most common color temperature for commercial businesses.",
    description11: "A 4100K lamp temperature appears much bluer compared to the 3500K lamp temperature.  This light is most often used in hospitals and office buildings.  This light temperature is better for performing fine motor tasks, reading and general desk work.",
    description12: "Much like the previous, a color temperature of 5000K appears bluer than the 4100K.  Although quite high on the color temperature scale, this is not the highest color temperature.  There are higher temperature lamps for uses such as industrial work, aquarium lighting and agricultural grow lights.",
    description13: "What is the Color Rendering Index?",
    description14: "The Color Rendering Index (CRI) is the measure of the ability of a specific light source to reveal the colors of objects in comparison with the ideal or natural light source.  This index has a scale ranging from 0 to 100, with 100 being the closest to a natural light source.  A light source that is generally 80 CRI or above is most commonly recommended for the best lighting results.",
    description15: "What is Lumen Output?",
    description16: "In simple terms, the lumen output is the amount of light omitted from a light source prior to being installed in a light fixture.  Most lamp packaging will come equipped with information comparing incandescent lamps against other types of lamp sources.  Most are familiar with incandescent lamps and the amount of light perceived to be omitted, which aids in identifying how the bulbs will differ from one another depending on the lumen output.",
    description17: "Hopefully the above aids you in finding the correct lamp, or other light source for your lighting application at home.  It may help to take a similar or burnt out lamp along with you on your search to be able to compare lamps for your application.  Often times this aids in knowing what wattage, lamp style or socket is appropriate.",
    description18: "Now go get creative with your at home lighting."
},

{

    
    id: 'firef',
    date: "August 17, 2016",
    img: automation,
    title: "Fire-Flow-Tests-How-&-Why",
    SEOTitle: "Fire Flow Tests, How & Why?",
    description: "Fire Flow Tests, also known as Hydrant Flow Tests can be performed for several different reasons.",
    description2: "Why?:In general, fire flow tests are conducted on fire hydrants to determine the water availability.There are multiple reasons why a flow test could need to be performed, below is a list of several of these reasons",
    description3: "To determine water availability in planning for firefighting activities.",
    description4: "To determine water availability for the design of fire sprinkler systems.",
    description5: "To determine water availability for the design of domestic water systems.",
    description6: "To evaluate development of water main extensions.",
    description7: "To evaluate system improvements and replacements.",
    description8: "To determine the general condition of the water distribution system by detecting closed valves.",
    description9: "Fire flow testing produces accurate water data which can be used for various purposes. Fire Fighting Agencies use this water data for training, planning and marking hydrants. This water data is also used for water system planning and design. Municipalities also use the water data to simulate high flow conditions, to determine pressure and flow-producing capabilities of the water distribution system and for calibration of hydraulic models.",
    description10: "How?:How often do Fire Flow Tests need to be performed on hydrants?",
    description11: "AWWA recommends flow testing all areas at least every 10 years (AWWA M17, chapter 6).",
    description12: "NFPA requires flow testing of underground and exposed piping at least once every 5 years (NFPA 25, Table 7.1.1.2, 2014).",
    description13: "How are Fire Flow Tests performed? There are two types of Fire Flow Tests:",
    description14: "Main Capacity Test determines the water supply availability in the water main. If you are designing a fire sprinkler system, use this test (residual hydrant + separate downstream flow hydrant).",
    description15: "Hydrant Capacity Test determines the flow-rate available from the hydrant and if it will deliver in a fire emergency situation. If you are performing fire flow tests of hydrants, use this test (residual hydrant and flow hydrant are the same one).",    
    description16: "For the purpose of this Blog we will only discuss how to perform a Main Capacity Flow Test, which is the two hydrant flow test. A Main Capacity Test evaluates the water supply of the fire main at the location of the test hydrant. The information derived from this test is used by city planners and contractors to consider the water supply for general use and fire sprinkler systems.",    
    description17: "Setup: At the test hydrant (pressure hydrant, static/residual hydrant):", 
    description18: "Attach gauge cap to test hydrant. Tighten all other caps.", 
    description19: "Open test hydrant, vent air from hydrant body through the valve on the gauge cap assembly. Close it when air is vented.",    
    description20: "Conduct the test",
    description21: "Record static pressure reading from gauge cap.",
    description22: "Slowly open hydrant using the gate valve to purge air from the hydrant. When hydrant is full of water, open gate valve to desired flow-rate (usually full open)",
    description23: "When the flow-rate stabilizes,",
    description24: "Record nozzle pressure from the remote reader.",
    description25: "and at the same moment",
    description26: "At the test hydrant",
    description27: "Record the residual pressure reading from the gauge cap.",
    description28: "At the test hydrant",
    description29: "Record the residual pressure reading from the gauge cap.",
    description30: "At this point, the test is complete.",
    description31: "Slowly close gate valve on flow hydrant, then close the hydrant. Remove test equipment from hydrant. Replace and tighten cap. If the hydrant is a dry barrel type, note that water drains properly from the hydrant.",
    description32: "Record the number of minutes that water was flowing. This can be used to account for the amount of water used during the flow test.",
    description33: "At the test hydrant",
    description34: "Close the hydrant. Remove gauge cap and replace hydrant cap. If the hydrant is a dry barrel type, note that water drains properly from the hydrant.",
    description35: "Now you know the How & Why of Fire Flow Tests a valuable tool in the engineer’s arsenal."
},

{
    id: 'beingaintern',
    date: "September 15, 2015",
    img: intern,
    title: "Being-an-Intern",
    SEOTitle: "Being an Intern",
    description: "An internship is beneficial in so many ways. My experience at R&W as an intern has given me direction and insight into the engineering field as well as provided me with valuable workplace experience. Before starting college I had no experience and very little knowledge regarding the engineering field and I began this internship not knowing what tasks or responsibilities that engineers encounter daily.  Throughout this summer with R&W I was given the opportunity to experience those tasks and responsibilities, as well as acquiring tools and a new skill set that cannot be taught in a classroom in college.",
    description2:  "Ive been educated on HVAC fundamentals and how they apply specifically to different jobs, as well as compiling information and putting together energy reports while following the proper energy codes. At R&W I have also had the chance to further my skills in technical writing, Microsoft Excel, as well as participating in basic tasks within the office setting that could apply to any various positions that I may hold in the future. In addition, I have strengthened my communication skills with both co-workers and executives. Asking many questions during this internship has gave me valuable insight regarding what a future job in mechanical engineering might look like.",
    description3: "When it comes to the working-world outside of college, there will always be difficult aspects of the job that you will struggle with. Transitioning from college to a full time 40-hour work week was something that I had yet to encounter. Finding a balance between sleep and longer work hours was also a challenge as I am prone to stay up later in the evenings. This schedule took a toll on me in the beginning as it was something that I was not accustomed to. I also found it challenging asking for help or clarification of a task. This act can feel very bothersome and I often felt like I was interrupting their task.  In hindsight, I learned that asking a lot of questions and getting clarification is good communication.  Throughout this experience I was able to catch a glimpse of the real work world and how I should expect to manage my time more productively.",
    description4: "Despite the sometimes challenging aspects of being an intern, there were various reasons it was enjoyable. At R&W, I was paid for my time, and discovered throughout the summer that many other internships were not paid, which was an added motivator. The smaller company size also enabled me to directly contribute to multiple projects in a direct way that a larger company may not have been able to.  Another reason I embraced being an intern at R&W was the friendly people I encountered. From the first day, I felt welcomed by the group of people that work here. Every morning I was greeted with kindly “Good Morning’s” and they treated me like an adult, something that I had yet to encounter.",
    description6: "As I prepare to finish my summer internship here at R&W, I reflect back and have gathered a few points of advice to future interns. The first being, it is okay to ask questions. Ask a lot of them. By asking questions, you are exhibiting that you are honest and need to be informed about something you don’t know. You also show that you have a desire to learn and to become better equipped to tackle the job in front of you. My second piece of advice is be willing to do the small tasks, the tasks that no one else wants to do. Cheerfully accepting jobs like taking out the recycling or organizing files says a lot about your character within the work place. Finally, show interest and be excited about the job that you are about to undertake. No one likes to hire or work with someone who is unenthusiastic.",
    description7: "Your potential internship can teach you a new software program or skill, it can help you realize which direction you want to go with your career, and it can give you a chance to use your already acquired skills to help others. This summer I was able to experience all of these, and in the end, I found my internship experience very valuable.",
},


{
    id: 'remotetroubleshoot',
    date: "July 30, 2015",
    img: troubleshooting,
    title: "Remote-Troubleshooting-Monitoring-SCADA",
    SEOTitle: "Remote-Troubleshooting / Monitoring SCADA",
    description: "Unless you had a nearly unlimited budget, your list of options regarding remote monitoring used to be quite slim. Since the invention of the internet, a world of possibilities has been opened and now that this technology is readily available to nearly everyone this task has become much easier to obtain. Through the invention of smart phones and portable tablets, we have become able to access an internet connection from just about anywhere. With the aid of this technology at our fingertips more and more operators are able to access their Supervisory Control and Data Acquisition (SCADA) systems remotely without the need of highly limited, proprietary, or custom devices.",
    description2:  "For years, OEMs (Original Equipment Manufacturers) have been required to make trips to the site in order to provide support.  But with a little forethought and the right infrastructure in place, they can now provide much of that support right from the comfort of their own office.  In fact, some OEMs (usually those from large corporations) may even REQUIRE the owner to furnish remote access for them – or at least offer a financial incentive to provide it.  And rightly so.  Depending on how far away they are, you could save a bundle on travel expenses alone, not to mentions the hours of ‘wasted’ time spent travelling that could be put to more productive use.",
    description3: "Although remote access is a wonderful tool, not every task can be done remotely.  Still, there are plenty of things that can that would justify the extra up-front cost.  And these days, much of that ‘extra cost’ has been greatly reduced to a palatable level; instead of costing “thousands” or “tens of thousands”, it’s more likely to be only “hundreds” (or less, depending on the complexity of the requirements needed or desired).",
    description4: "Historically, the main question that many asked is “How does one remotely connect to a site?” There are many factors that can play a role in how this question is answered, one specific example involves a remote site with no communication infrastructure for miles. There are several viable options regarding this particular example. A telephone line can be installed, assuming you have a right-of-way or easement from the point of utility connection to the site. This may not be a suitable option for remote needs of a farther distance, as it can become quite costly sometimes spending thousands of dollars. Radio is also another option that can be discussed. To be considered it would be best to have a clear line-of-site path, if this is unobtainable repeater stations can be used to maneuver obstacles. Fortunately, if you choose this method there are license-free frequencies that can be used to avoid any additional costs for this service. The evolution of the smart phone has also broadened the scope to allow remote sites to have sufficient cell coverage, supporting data transfer. Satellite transceivers are another option to be considered and can be used where cell phone coverage is still limited. However, depending on budgetary constraints it may land on the higher end of the scale. Using Cable Television could also be a suitable option as they have been branching out into the telecommunications market.",
    description6: "Eventually, these options must have a destination. Traditionally, the most popular choice has been the Master Telemetry Unit (MTU) and unit would generally be located at the company’s main facility. The MTU would come with a compatible Remote Telemetry Unit (RTU) that would be housed at the remote site. However, over time these units were replaced with dedicated Programmable Logic Controllers (PLCs) that handled the data communications between several locations. At the time this seemed to be the most logical step considering that most facilities were already facilitating PLCs for their automation and control needs. Today, Ethernet modems and radio modems are used extensively to provide a Wide Area Network (WAN). This network connects sites grants the ability to look just like another connection on the Local Area Network (LAN) at the main facility. Using this type of remote access a Virtual Private Network (VPN) can be administered and will provide a secure network connection, effectively extending the LAN/WAN connection anywhere in the world.",
    description7: "Generally speaking, the more complex or critical the process is the more need there is to become remotely available to monitor and troubleshoot. Fortunately, with today’s technology, remote monitoring and troubleshooting has become easily obtainable.",
    description8: "If you currently have a facility without remote monitory capability and would like to know what options we have to add functionality to your space, please give us a call. We would be glad to discuss remote access options with you.",
},

{
    id: 'utilitycoordination',
    date: "May 19, 2015",
    img: utilityCoordination,
    title: "How-Detailed-Utility-Coordination-Benefits-Your-Project",
    SEOTitle: "How Detailed Utility Coordination Benefits Your Project",
    description: "Surprises. They’re wonderful when it’s your birthday or when a coworker brings in a sweet treat to share. (Voodoo Doughnuts anyone?) However, they’re not so welcome when a project goes to construction. The last thing anyone wants to deal with is a utility surprise in the field that sends the construction manager and client into a panic. These kind of surprises can significantly delay, or in extreme cases, kill a project.",
    description2:  "How can we minimize those unwelcome surprises in the field?",
    description3:  "The answer is surprisingly simple: Detailed utility coordination.",
    description4: "Including the serving utilities into the planning process early helps keep surprises that effect the project’s timeline and final budget to a minimum. Painting a clear picture from an existing service source to your proposed project site will help clarify issues that may go unseen until you’re ready to break ground.",
    description6: "Utilities have an insight into other pending projects in the area; whether it’s a new residential development, a commercial property, a future utility system improvement or something else in their pipeline. It’s information that could affect your pending project. Do they have the service size you’re after? Will there be enough availability or is their current system maxed out? Will new service require additional time for the utility to upgrade their existing system?",
    description7: "Scope of work varies from utility to utility. Some will bring the new service to your new front door for a fee, some will end at the property line for a smaller fee, while others will require the customer to complete all the work from their existing system to the project site. That could require using a utility approved contractor, work in the right-of-way (which will require special permitting), crossing a third party property (requiring an easement from the property owner), crossing a bridge/canal/stream (all which can require special permitting), and/or running across an environmental constraint (i.e. wetlands, protected plant/animal, contaminated soils, etc). These are all items that run the risk of impacting a project’s timeline and budget. If notified early enough in the project most issues can be sorted out with the utility to find a solution that works for everyone without impacting the construction schedule. That’s not always the case when these issues pop-up at the start of construction. At that point most designs, permits and easements are set.",
    description8: "With a detailed utility approved design in hand, you have the advantage of including this information on your design drawings. In the design you have the following listed:",
    description9: "A path outlined to ensure you have an easement in place to cover the route, along with the utility’s requirements for said easement.",
    description10: "A list of the supplies and equipment needed. Identifying which ones the utility will provide and which need to be provided by the customer or their contractor. The specified equipment and provided distances (thanks to scaled drawings) will also allow contractors to submit a more accurate bid. Minimizing the need for change orders in the field.",
    description11: "A list of fees (application, hook-up, membership, special construction, etc) the utilities will require. All which can be incorporated into the budget before construction starts.",
    description12: "Outlined requirements per utility, including a point of contact for the construction manager. Having a shortcut to the person already familiar with the project, thanks to the utility coordination, the project manager just has a single person to contact to coordinate preconstruction meetings, inspections and final installation requirements. This helps maintain a smooth schedule for construction.",
    description13: "With all the benefits to coordinating utilities early, and in detail, it makes you ask the question … what are you really saving by skipping it?"
},

{
    id: 'odotsisters',
    date: "Feb 23, 2015",
    img: sistersmaintance,
    title: "ODOT-Sisters-Maintenance-Building-Taking-the-Long-View",
    SEOTitle: "ODOT Sisters Maintenance Building - Taking the Long View",
    description: "Can there be anything cool and blog-worthy about a maintenance garage with support offices in the high desert of Central Oregon? Generally, no there cannot. But in the case of the ODOT Sisters Maintenance Building the answer would be a resounding YES. And not just because R&W was the MEP engineers on the project but because there are some good ideas on how to evaluate cost and how to use systems that can better inform all building owners and engineers about how to view buildings and costs.",
    description2:  "The Building: This project was a 10,000 square foot Maintenance and Office Building with 6,500 square feet of maintenance bays and support areas with heating and ventilation only. The remaining 3,500 square feet were office spaces with full HVAC.",
    description3:  "Connecting Solar and Geothermal: The primary source of heat was geothermal that included preheating by solar. This solar thermal system served a dual purpose, generating both heating water and potable domestic hot water for showers and office kitchen uses. Both heating water uses were supported by water to water geothermal heat pumps. All cooling for the offices was from the geothermal water to air loop. This combination of using solar for heating as the primary source with back up from geothermal combined two very efficient heating sources to create an efficient very low carbon footprint heating system. Each geothermal zone, office HVAC, heating water, domestic hot water, was provided its own geothermal ground tube system, allowing efficiencies in pump energy as a loop and only active when needed.",
    description4: "Only Heat Where and When Needed: Heating of the service bays has two critical components. First was heating for worker comfort, second was heating to ensure that the sand in the sanding trucks did not freeze before it could be applied to roads. This was compounded by the fact that the large bay doors would be opening often and sometimes left open at which point no heating was desired for energy saving reasons. This unique set of needs led to a unique solution. Two separate heating systems were installed. For general space heating an underfloor radiant system was installed that was fed from the solar/geothermal source. This provided heating to the working on the floor where it is most needed. Each bay was designated as a zone with automatic shut off of the floor heating when the bay door is open. A propane fired infrared heating system was provided over the sand truck bays that is manually operated by the maintenance staff only when needed. This heat is directed only at the top of the truck where and when it is needed.",
    description6: "The Long View: Considering the cost of these unique options and solutions to interesting design issues ODOT took the long view when considering the costs and benefits. This building was being designed as a 50 year building so first cost, while important, was not the only or even the primary factor in determining which choices to make. Paybacks within the 50 year life of the building were considered as worthy of consideration. If ODOT had been first cost driven they would have likely reduced installation cost significantly and perhaps saved some energy over the short term. But as system replacements become necessary and over the life of the building these costs would have been greater and greater. So in taking the long view ODOT saved money and energy while having a very small carbon footprint in the process.",
    description7: "How this Applies to You: R&W understands that not everyone or every owner has the resources of ODOT to take a 50 year view of a building. But everyone does have the ability to look beyond first cost and consider unique solutions that might cost more initially but provide benefits in the future. Not all can or must be accepted but all can be considered and discussed. An open mind and a longer view than first cost, is all that is needed to explore options.",
},

{
    id: 'lessonincfd',
    date: "October 15, 2014",
    img: lessonCFD,
    title: "A-Lesson-in-CFD",
    SEOTitle: "A Lesson in CFD",
    description: "There are certain moments in life when you see something and it just speaks to you. The first time I saw Computational Fluid Dynamics (CFD) in action, was one such time. I was watching a television show on Boeing Aircraft manufacturing. They were building a new jetliner and the documentary took the viewer behind the scenes to divulge how they come up with the design for a new jetliner. There was a segment on the shape of the wing. The goal was to reduce weight, increase lift, decrease drag; in turn these attributes would decrease fuel consumption, and increase efficiency. They used computers to simulate air moving over different shaped wings and could tell from these models which ones would be best suited for real world prototypes. Prototypes are extremely expensive to build.",
    description2:  "After the show had concluded, I would think from time to time how fascinating that technology was, more specifically their use of CFD. My career provided me the opportunity to learn the CFD Analysis and design program. I am intrigued that it can save energy therefore creating value, make less of a carbon footprint by using less material goods and thus making an environmental impact Being Green.",
    description3:  "CFD in its simplest form, is about describing the motion of a fluid, such as air, or water about an object. At its most complex, it can describe, in great detail, how fluid will transfer heat, transfer static electricity, change viscosity, produce sound, generate lift, how the water in your toilet will spin, how the water in the oceans will circulate, and even, how it will feel to be somewhere. It has been used for things as dynamic as solving aviation disasters, or space accidents. And as simple as, how your water mixes inside your faucet.",
    description4: "Automakers often use CFD to design cars down to the minute details, such as shape of the wiper blades reducing the cross section of the vehicle. These aerodynamic attributes save us money. A simple test one can do, not while driving of course, is to put your hand out the window of a moving car. Position your palm so it is facing forward in the vehicle, and feel how much energy it takes to hold it in place. Now turn your palm face down, you will notice that it is a lot easier to hold your hand in place.",
    description6: "CFD can be used to simulate stress of water over time on a bridge, or how air will interact with the bridge, think Tacoma Narrows Bridge. It can be used to make buildings safer, such as wind strength, or how quickly smoke will dissipate in a space enabling people to breathe.",
    description7: "This technology has become essential in the design industry for designing ships, aircraft, automobiles, wind turbines, even spacecraft that interact with the atmosphere in any way. As often as CFD is used, there are even more applications where it could be used, but is not. Besides external design of a building, the inside of a building can be refined with CFD to provide maximum efficiency of the HVAC system, such as a Data Center. It can be used to view the air dynamics inside a sun-facing atrium in order to minimize energy usage to cool the space, or likewise heat a space, in Operating rooms controlling spread of contagions via air routing and ducting. Other applications such as hydro dynamics in a fishery, clean room particulate prediction and control, or building offices or buildings for allergen containment.",
    description8: "The study and practice of CFD indirectly benefits us all on a daily basis. In the future, CFD will be used more widely in conjunction with like technologies such as simulation mechanical in designing parts for strength, while minimizing material needed and energy to build and therefore decreasing environmental impact. As the technology has evolved over the years the price has come down. With this combination, CFD is the next logical step in being healthier and green.",
},

{
    id: 'lowhangingfruit',
    date: "September 15, 2014",
    img: LowHanging,
    title: "Low-Hanging-Fruit-Energy-Upgrades",
    SEOTitle: "Low Hanging Fruit Energy Upgrades",
    description: "Would you rather walk 1 mile to get $100 or 100 miles to get $1? Except for an extreme walker, this question is a no-brainer. Just as water flows downhill and as nature abhors a vacuum, we all naturally take the option with the biggest reward and least amount of effort. This same analogy applies to a building owner or tenant who is interested in making upgrades and investments in their building to save energy. We all want the biggest bang for our buck. Since R&W’s founding, we have been helping building owners analyze building upgrades. In that time we have seen the following four consistently rise to the top.",
    description2:  "Retro-commissioning: Just like us, building systems get old over time and stop working correctly. Retro-commissioning is like a complete physical for a building’s energy using systems to see what has failed or is limping along. It is amazing how often we find things such as exterior lighting on during the day, a broken damper linkage, a leaking coil or pipe in a basement, ventilation dampers held open with a 2×4, closet lighting on 24/7, a desk moved in front of a return air grille or programmable thermostats keeping full heating on at night. Often these problems can be corrected relatively inexpensively with huge energy savings.",
    description3:  "Lighting: LED is steadily making advances. Many of our clients have been getting great payback by replacing inefficient high pressure sodium, incandescent or metal halide exterior lighting with LED lighting which uses a fraction of the energy. We are also seeing more customers replacing interior lighting with LED fixtures as the cost continues to drop. LED does not need replacement as often which saves on O&M costs. Low-wattage T5 or T8 fluorescent fixtures are great to replace old T12 or metal halide interior fixtures.",
    description4: "Control Upgrades: Many building owners are getting good payback from replacing their old leaky, pneumatic HVAC control systems with modern, digital, web-accessible controls. Energy saving features can easily be added such as installing CO2 sensors to turn down ventilation dampers, automatic indoor temperature adjustment based on outside temperature, intelligent morning warm-up that learns your patterns and occupancy sensors to activate things on only when people are present. A side benefit is that maintenance staff can be alerted to problems via their smart phones on a cold winter night and often address the situation without leaving home. Controls for building security, lighting and HVAC can all be integrated to work together. Increased range on wireless technology helps bring down the replacement costs as well.",
    description6: "Easy Building Shell Upgrades: No offense to the triple layer window salesmen going door to door but window replacement generally has a long payback time. Much more effective on one’s wallet is installing interior adjustable blinds and exterior shading devices that block the sun in summer but not in winter. Adding additional insulation to a poorly insulated attic space or a floor over an unconditioned crawlspace has a great return on investment, provided the existing structure doesn’t need to be opened up.",
    description7: "The great news is with all the incentive money available from the state and utilities, now more than ever is a great time to make improvements to your building. The incentives available make the payback on qualifying energy upgrades even faster and encourage people to make these wise investments. Let us use our experience to help you save money, save energy and improve your building.",
    
},

{
    id: 'casualforacause',
    date: "July 5, 2014",
    img: cause,
    title: "Casual-for-a-Cause-Fridays-Hits-a-Milestone",
    SEOTitle: "Casual for a cause Fridays Hits a Milestone",
    description: "leven years ago, R&W Engineering began a tradition that would impact many lives for years to come. Casual Friday for a Cause not only allotted for the employees to dress in their favorite comfortable pair of jeans on fabulous Friday, but also asked that each employee donate five dollars to the selected charity of the quarter. The employees agreed together this could be an opportunity to give back and make a difference. Each quarter R&W employees vote on a charity and all the money raised during that quarter is donated to that charity. R&W employees fund local charities as well as nationwide organizations. Over the last 11 years, R&W employees have donated over $30,000 to different charities and organizations. Some of the different charities R&W has been a part of are the American Heart Association, Royal Family Kids camp, Oregon Food Bank, Mercy Corps, Dove Lewis Animal Hospital, Sports Outreach and many more. Casual Friday for a Cause is a wonderful opportunity to involve ourselves with our community beyond our office walls.",
    description2:  "Some of our most memorable contributions have gone to Cassie’s Angels and the J.P. Carlisle Foundation. Cassie’s Angels is a foundation organized to financially and emotionally support a seven year old girl battling a rare cancer call neuroblastoma. Our donations went to the research as well as medical expenses for this family. The J.P. Carlisle Foundation was a charity set up for a US Marine who suffered a traumatic brain clot while on assignment. The funds raised at R&W helped to cover medical expenses for J.P. and his family.",
    description3:  "Other organizations are the Oregon World War II Memorial and Home Plate Youth Services. The WWII memorial pays a deep respect and appreciation to the thousands of Oregonians who gave their life during this war and our support in this charity has helped with maintenance of the memorial. Home Plate Youth Services charity assists children up to the age of 24 who are homeless or in unstable living conditions. This organization provides meals, resources, access to education, and so much more to thousands of children in need.",
    description4: "As a donating employee, I must say the dollar amount is quite impressive. It is hard to imagine just $5 a week was able to contribute to all of that. However, beyond the numbers of money donated are the smiling faces and happy hearts of those whose lives were impacted by a simple five dollar bill. I am happy to say that I am a part of an organization who values the lives of others, and those in need within our community.",
},

{
    id: 'enginerd',
    date: "June 11, 2013",
    img: enginerd,
    title: "The-Enginerd",
    SEOTitle: "The Enginerd",
    description: "The Enginerd. He is the unfortunate result of unofficially adventurous tedium’s of engineering combined with the additionally tiresome cross-referencing of restrictions placed by countless numbers of officials and experts tying hands at every turn to collate into a vortex of nerdism equating to high level thought processes combined with exceedingly dull, monotonous, diminutive, inter-personal skills and outrageous conceptualizations. His mission is to solve the physical problems of societal infrastructure to not only maintain, but improve the quality of life for both the private and public sectors. It’s just that simple…or is it?",
    description2:  "We join one such Enginerd tasked with reconfiguring a new private sector system to comply with the public sector rules, regulations and guidelines for sustainable green power generation in a local area. This unprecedented project yields the ability to utilize energy from the local infrastructure instead of just discarding the energy it stores as a byproduct through conventional means in order to reduce excesses that would create problems for the end users. And though some scorn the thought of attempting such ventures citing the laws of physics as not allowing the project to be fruitful, those involved understand the entire system and why such a project could revolutionize sustainable power with low environmental impact for many areas of the modern world.",
    description3:  "Though the concept is relatively simplistic, the application of such a venture is anything but simple. Sophisticated and specialized equipment is necessary to perform this power generation. The Enginerd must review the necessary processing equipment to be used then determine the additional components required so that it is not only functional but tolerable to local, state and national jurisdictions. Add to the complications, the virtually non-existent available real-estate in the only location permissible for installation of the project, and the Enginerd has been placed face to face against an unwavering bureaucracy of foes.",
    description4: "A technical solution to compact and minimize impact is not enough for this project. The Enginerd must argue the interpretation of laws, codes and regulations with the same entities wanting the project to succeed because of aesthetics! How will this ever result in a successful project? Fear not, a solution is at hand.",
    description5: "Upon hours of reflection and turmoil in devising a course of action to appease the lords and ladies of public office presiding over final acceptance adherent to their criteria, an acceptable solution emerges from the shadows of the mind. Eureka! With the majority of the equipment located underground, the remaining equipment can be hidden from direct site through the use of expensively extravagant art.",
    description6: "The plan is set in motion. All parties involved agree satisfaction has been achieved. The project is a success! “We have done it!” the Enginerd exclaims. But within seconds of this outcry of relief, an email appears in the Enginerd’s inbox with the subject line: Electrical Inspector Comments. Upon examination of the email the Enginerd drops his head in reflectance of defeat, then slowly raises it all the way back as he inhales deeply, then screams, “Curse you NEC!!!"
},


{
    id: 'humansnumbers',
    date: "April 18, 2013",
    img: humansnotnumbers,
    title: "Humans≠Numbers",
    SEOTitle: "Humans≠Numbers",
    description: "Imagine a workspace of twelve-by-twelve cubicle after twelve-by-twelve cubicle filling the entire floor space. Common thought would consider this a boring place, not because of its lack of interesting features, but because of its sameness. Its sameness with all other offices in the world. The current method of herding and stabling the worker: accepted by all; liked by few. The lunchroom is a small, brief respite in the vanilla plain world, where the difference allows an openness otherwise neither considered nor accepted. “Can you believe that John is a department manager?” Asks one. “Yeah, if people were numbers on a spreadsheet or in an equation he might actually be good at it.” Another replies.",
    description2:  "This is John’s domain; here he is king. A place where the laws of physics are supreme, where Bernoulli, Watt, Mohr, and others defined reality hundreds of years ago. He had proven himself an excellent engineer and been rewarded with his own serfdom. He would conquer this like he had engineering, merely by applying the rules and obtaining the desired outcome. This was not a difficult assignment, others had succeeded, and those who failed had clearly not properly applied the laws. As for workers who do not fit in, they are merely rounding errors. Ignore them, give them the undesirable project and soon enough they will leave.",
    description3:  "In spite of the externalities most people are content, if not happy here. The engineering is interesting; the co-workers enjoyable. In general this place is as good as any to spend the required time among the employed. That is if you are not considered a rounding error. For those who choose to rebel against the sameness of this kingdom life is quite miserable. Yet the true problem lies not in those who rebel continuously but in the fact that human thoughts and behavior do not always obey the laws of physics that John would have rule this place. So everyone at one time or another (because independent thought and emotions cannot be quelled) at least visits the realm of the rebel.",
    description4: "When people cannot control that which makes them more than calculable figures, a confrontation with John will occur. Since no one has complete control of their humanness, emotions or thoughts, confrontation with John is inevitable. People either conform or leave; things continue to be the same. John, through lack of any introspection or lasting opposition, gains more power which reinforces his belief that people are numbers and he is as good at managing people as he is at engineering. The average worker remains relatively happy in spite of him.",
    description5: "This all too familiar narrative describes most engineer/managers to some extent. We must remember that people do not, in fact cannot, fit into equations. Just because ‘C’ looks like ‘A’ and ‘B’, they are not necessarily all the same. To use a concept that is criticized as fad by some and completely adopted by many in the management and leadership community the engineer/manager must know and improve their Emotional Intelligence. A good place to start would be using this psychtest evaluation tool. It will likely be eye opening and provide some feedback to fuel positive introspection on how you relate to employees, co-workers, clients, vendors, sub-consultants, and even family.",
},

{
    id: 'greenconstruction',
    date: "January 27, 2013",
    img: GreenEnergy,
    title: "Financial-Incentives-for-Green-Construction",
    SEOTitle: "Financial Incentives for Green Construction",
    description: "In the recent movie ‘Lincoln’ by Steven Spielberg, Abraham Lincoln is faced with a difficult choice that will affect millions of lives, current and future. The Civil War is in its fourth year, Lincoln has just been reelected to a second term and the Confederate states have come to him with an offer of surrender. The catch is that they are asking him to repeal the 13th amendment which outlaws slavery. The path of least resistance, based on many of the voices, would be to end the war immediately by repealing the amendment and allowing slavery to continue. As we know from history, Lincoln, made the hard choice to keep the amendment, thereby prolonging the war. He stood firm for what he believed was right.",
    description2:  "While the moral choices are not as stark in engineering, we are frequently faced with a choice to take the path of least resistance by designing or installing the least expensive, least efficient building systems available. In most situations it is found that by spending a little more up front for a more efficient installation, building owners will save money in the long run. Fortunately there are many energy incentives that will make this choice easier.",
    description3:  "The energy incentives fall into three categories: rebates/grants, tax credits, and tax deductions. These incentives are frequently enough to allow the owner to ‘pull the trigger’ on a more efficient project than they otherwise may have done.",
    description4: "Rebates and grants are money that is given directly to the owner before (grants) or after (rebates) the project has been completed. ARRA, Oregon Department of Energy’s (ODOE’s) SB1149 program, Energy Trust of Oregon (ETO), BPA, Clark PUD, EWEB and many other local utilities will pay a certain percentage of the total project cost based on the annual calculated energy savings. These incentives typically pay for 10%-50% of the entire project.",
    description5: "Tax credits are reductions in the tax owed by the owner based on the annual energy saved. In Oregon, under the EIP (formerly BETC) these tax credits will pay for 35% of a qualifying project. Owners with no tax liability are able to auction off their tax credits to the highest bidder.",
    description6: "Finally, the federal government offers a tax deduction for qualifying projects. This deduction through the IRS reduces taxable income by $0.30-$1.80 per square foot of the affected building.",
    description7: "One example is a recent project R&W completed for the Oregon Trail School District. As part of ODOE’s SB1149 school efficiency program, R&W conducted energy audits on all 10 schools in the district. From these studies, the district was able to identify and quantify multiple energy upgrade projects at each school, including replacing inefficient boilers, delamping over lit areas, upgrading lighting controls, replacing single pane windows and upgrading old pneumatic HVAC control systems to modern digital controls. As a result of these studies, ODOE in partnership with ETO was able to provide the district substantial incentives to help complete these improvements. These energy upgrades will result in lower utility bills, lower operation and maintenance costs and more comfortable classroom environments.",
    description8: "While we don’t face moral choices as encompassing as Abraham Lincoln, we are all faced with many small choices every day. Will we take the path of least resistance or will we implement energy efficient practices to reap benefits in the future? Thankfully, the incentives available make the choices easier for us. The benefits reaped will affect generations for years to come."
},


];